### ISSUE TITLE
Troca do Repositorio de Current User para Local Machine

### ISSUE THREAD

**Issue by clsaad** [ACBrNet/ACBr.Net.NFSe#104]
Boa Tarde,

Gostaria de sugerir a mudança no ACBR.NET.DFE.CORE da função de Selecionar Certificado para pesquisar no Local Machine ou permitir a importação de um arquivo do tipo PFX.

Com isso, será possivel a utilização do componente para emissão de NF utilizando ambientes de hospedagem, pois como lê do Current User, obrigatóriamente tem que configurar o IIS com o usuario na qual tem o certificado instalado, o que não funciona em ambientes compartilhados.

Obrigado,

**Comment by rftd** [comment]
Não vejo a necessidade de mudar isso e é possivel carregar o certificado tanto por path quanto por byte[].

**Comment by clsaad** [comment]
Parceiro, ignora. Fiz o update para a ultima versão dos pacote via nuget e consegui testar usando o pfx localmente.
Tenho outra situação de nao estar trazendo no formato do SmarapD de Americana, mas vou continuar as configurações.
Gratidão.

**Comment by rftd** [comment]
O provedor SmarAPD tem mais de um formato Americana usa um formato que ainda não foi implementado.
