### ISSUE TITLE
A3 está funcionando

### ISSUE THREAD

**Issue by nielson266** [ACBrNet/ACBr.Net.NFSe#106]
Boa Tarde, está funcionando o A3 nesse projeto, estou com a3 token e coloquei o serial mais não encontrar o certificado.
Alguém poderia ajudar.

**Comment by rftd** [comment]
o metodo de acesso a certificado a1 e a3 é o mesmo, não tem diferença entre os métodos de acesso a certificados do repositorio.

**Comment by nielson266** [comment]
@rftd obrigado, por responder, peguei o projeto modelo, mais coloquei o número do serie e não encontra, estou usando o A3 token, o processo é esse mesmo, usando o só o número de série?

**Comment by rftd** [comment]
sim, é o mesmo se não esta achando o mesmo não deve estar instalado no repositorio do usuário.

**Comment by rafd75** [comment]
Boa tarde @nielson266  --- eu uso o A3 aqui ... é cartão, mas acredito que seja a mesma coisa.

Para "pegar o serial", uso o seguinte código (está em Foxpro, mas verifique o código na classe Proxy do ACBR)
```
oNFSE = CreateObject("AcbrNfseProxy")
Store "" To msgAlerta, msgErro
m.Certificado = oNFSE.SelecionarCertificado(@msgAlerta, @msgErro)
```

**Comment by nielson266** [comment]
@rafd75 o que era estranho que ele não estava aparecendo, mais atualizei a cadeia de certificado e apareceu para selecionar, certificado e peguei o serial.

Vlw galera pela ajudar

**Comment by rftd** [comment]
é que sem a cadeia é considerado invalido por isso não aparece.
