### ISSUE TITLE
Pago para quem desenvolver DBSeller

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#109]
Boa noite pessoal,

Alguém interessado em desenvolver o provedor DBSeller ?

Quem estiver com tempo e quiser devenvolver, me avise que eu pago.

Dados de uma cidade do provedor:
[4321600]
Nome=Tramandai
UF=RS
Provedor=DBSeller
NomeURL_H=http://hom.nfse.tramandai.rs.gov.br
NomeURL_P=http://nfse.tramandai.rs.gov.br

**Comment by Transis-Felipe** [comment]
@rftd Tem interesse ?

**Comment by rftd** [comment]
Eu acabei de finalizar um refactory que tava promovendo no componente, eu posso dar uma olhada neste provedor.

**Comment by rafd75** [comment]
@transis2 , se o Rafael conseguir encaixar na agenda dele, pode contratar... 

Fiz isso no provedor do RJ (se não me engano)... me entregou no prazo e praticamente quase todo funcionando (eu fiz os testes com o certificado do cliente, anotei os problemas e na rodada seguinte, tudo funcionando.)... 

**Recomendo!!!**

**Comment by Transis-Felipe** [comment]
@rafd75 obrigado pela dica!

@rftd, quanto tu cobraria ?

**Comment by rftd** [comment]
@transis2 entra no [gitter ](https://gitter.im/ACBrNet/ACBr.Net.NFSe?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
