### ISSUE TITLE
Limpeza do codigo e otimização.

### ISSUE THREAD

**Issue by rftd** [ACBrNet/ACBr.Net.NFSe#112]
- [X] Remoção de classes e interfaces que não serão mais utilizadas.
- [X] Renomear a classe NotaFiscal para NotaServico.
- [X] Renomear a classe NotaFiscalCollection para NotaServicoCollection.
- [x] Revisão e limpeza do codigo.

**Comment by Transis-Felipe** [comment]
Oi, fui testar o projeto para ver como ficou após o refactor mas deu um erro.

Eu coloquei em comentário para poder compilar, mas se quiser dar uma olhada, aí está o print.

![image](https://user-images.githubusercontent.com/4941173/93606414-67369200-f99e-11ea-89eb-ac615c07663c.png)
