### ISSUE TITLE
Exception no provedor Fiorilli após refactor

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#116]
Estou testando o projeto após o refactor e encontrei problema no provedor Fiorilli

Declaração XML inesperada. A declaração XML deve ser o primeiro nó no documento e não pode haver espaço em branco antes dela. Linha 1, posição 178.

![image](https://user-images.githubusercontent.com/4941173/93900061-5900b280-fccb-11ea-985a-f186087626c7.png)

Tela com os dados utilizados no projeto Demo
![image](https://user-images.githubusercontent.com/4941173/93900270-906f5f00-fccb-11ea-9399-5b92db266870.png)

**Comment by rftd** [comment]
Já sei o que é vou ajustar isso de forma correta, já devia ter feito isso a um tempo

**Comment by Transis-Felipe** [comment]
Show
