### ISSUE TITLE
Implementação SIGISS - Marília-SP

### ISSUE THREAD

**Issue by danilobreda** [ACBrNet/ACBr.Net.NFSe#118]
Hoje tenho a necessidade de implementar esse serviço:
[https://marilia.sigiss.com.br/marilia/index.php](https://marilia.sigiss.com.br/marilia/index.php)
[https://marilia.sigiss.com.br/marilia/ws/sigiss_ws.php?wsdl](https://marilia.sigiss.com.br/marilia/ws/sigiss_ws.php?wsdl)

Vou realizar a implementação aqui para um pullrequest futuro.. porem estou com algumas duvidas para escrever o código...

Verifiquei que ele é diferente do SIGISS que tem na pasta schemas, caso eu implemente esse service, devo eu colocar em uma pasta especifica junto ao nome da cidade? EX: SIGISS_Marilia
O mesmo serve para a pasta schema?

**Comment by rftd** [comment]
Não tem SigIss na pasta schemas.
Crie como SigIss mesmo, que eu saiba este provedor tem Layout Próprio e nem schemas tem.

**Comment by danilobreda** [comment]
@rftd combinado, vou criar e validar durante essa semana, e encaminho um pullrequest para sua analise.

**Comment by danilobreda** [comment]
@rftd vou aguardar o lançamento do Nuget dessa versão do pull #120. Já com o SIGISS para utilização no meu sistema.

**Comment by danilobreda** [comment]
Vou fechar a issue pois foi implementado com sucesso.
Caso for possível, lançar o nugget para eu utilizar o mesmo no meu sistema.

**Comment by rftd** [comment]
eu estou terminando os ajustes, assim que terminar subo e aviso aqui para testar
