### ISSUE TITLE
Servidor rodando .NetCore sem suporte a SSL3 com erro de uso da biblioteca.

### ISSUE THREAD

**Issue by danilobreda** [ACBrNet/ACBr.Net.NFSe#119]
Estou implantando um novo serviço #118 porem ao realizar alguns testes do codigo que fiz, na seguinte linha de código acontece um erro de "protocolo não suportado", infelizmente verifiquei que não existe como eu instalar SSL3 no servidor pelo [mesmo estar deprecated.](https://ma.ttias.be/rfc-7568-ssl-3-0-is-now-officially-deprecated/).

Gostaria de saber qual a maneira de seguir, pois até agora eu comentei o código como abaixo:

![image](https://user-images.githubusercontent.com/14843499/95265714-23e67b00-0808-11eb-9bf3-ce081ff634f5.png)

Acredito que esses protocolos poderiam ser uma propriedade da configuração que pode ser alterada.
Ou deixar a propriedade da classe, publica, hoje esta private como segue imagem:
![image](https://user-images.githubusercontent.com/14843499/95265827-6314cc00-0808-11eb-901c-dccc0b20b119.png)

Aguardo uma solução 👍  e caso queira, eu modifico e jogo junto com o pullrequest depois.

**Comment by rftd** [comment]
Estranho geralmente a comunicação começa com o tls 1.2 e não com o ssl3

**Comment by danilobreda** [comment]
Na verdade ele nem bateu no serviço... na hora de setar `ServicePointManager.SecurityProtocol = protocolType;` ele da o erro... quando tiro o ssl3 ele funciona (igual da imagem)

**Comment by rftd** [comment]
deve ser algo especifico do .net core neste caso temos que colocar uma diretiva ai.

**Comment by rftd** [comment]
Eu mandei uma atualização que deve ajudar ai.

**Comment by danilobreda** [comment]
Resolvido!
