### ISSUE TITLE
MaxReceivedMessageSize erro

### ISSUE THREAD

**Issue by martinlietz** [ACBrNet/ACBr.Net.NFSe#121]
fiz um clone do projeto e estou recebendo essa mensagem de erro:
The maximum message size quota for incoming messages (65536) has been exceeded. To increase the quota, use the MaxReceivedMessageSize property on the appropriate binding element. Pelo que vi tem que ajustar no app.config mas este projeto não tem um arquivo app.config

**Comment by martinlietz** [comment]
NotaCariocaServiceClient.cs linha 203

**Comment by rftd** [comment]
Esta classe so tem 163 linhas

**Comment by martinlietz** [comment]
Tens razão esta na base class , ACBr.Net.NFSe\src\ACBr.Net.NFSe\Providers\NFSeServiceClient.cs 
class NotaCariocaServiceClient : NFSeSOAP11ServiceClient : NFSeServiceClient

**Comment by rftd** [comment]
Subi algo que pode te ajudar nisso ai.

**Comment by martinlietz** [comment]
Deu certo, só faltou um pouquinho eu mudei para 
 if (!(Endpoint?.Binding is BasicHttpBinding binding))
                return;

            binding.MaxBufferPoolSize = int.MaxValue;
            binding.MaxBufferSize = int.MaxValue;
            binding.MaxReceivedMessageSize = int.MaxValue;
Não consigo subir, não tenho permissão.

**Comment by martinlietz** [comment]
Voce fechou, mas acho que faltou subir minha mudança, como falei eu não consegui.
