### ISSUE TITLE
 Could not establish trust relationship for the SSLTLS secure channel with authority 'marilia.sigiss.com.br' #3 

### ISSUE THREAD

**Issue by danilobreda** [ACBrNet/ACBr.Net.NFSe#122]
Estou com esse problema em ambiente linux apenas... (produção)
Lembrando que o ambiente de marilia sigiss ele nao tem certificado... porem ele tem uma conexao TLS ao endpoint 'marilia.sigiss.com.br', e isso que esta dando problema acredito.
[referencia](https://stackoverflow.com/questions/55620230/could-not-establish-trust-relationship-for-the-ssl-tls-secure-channel-with-auth)
No Zeus DFE eu tive o mesmo problema em situações onde o ambiente era linux, vou tentar testar para verificar o problema e faço um pullrequest pra vc analisar!

**Comment by rftd** [comment]
no caso o certificado do servidor não pode ser validado no cliente é isso neh ?

**Comment by danilobreda** [comment]
> 
> 
> no caso o certificado do servidor não pode ser validado no cliente é isso neh ?

Isso, porem não estou entendendo muito porque o mesmo acontece apenas em linux, estou tentando criar um ambiente linux local mas está complicado kk

**Comment by rftd** [comment]
é que no linux usa OpenSSL deve ser por isso o problema, vou ver uma mod aqui e te passo para testar.

**Comment by danilobreda** [comment]
Erro detalhado: 

> error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small

Após uma pesquisa verifiquei que esse servidor em particular do Sigiss de marília utiliza um Certificado para conexão HTTPS com um tipo de **cifra** antiga e com vulnerabilidade atualmente...
O Openssl do linux(versões mais recentes) não permite esse tipo de conexão por default! Por isso para resolver o problema tive que modificar o arquivo  /etc/ssl/openssl.cnf

De:
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```

Para:
```
[system_default_sect]
MinProtocol = TLSv1
CipherString = DEFAULT@SECLEVEL=1
```

No **Debian** utilizei o seguinte código:
`sed -i 's/TLSv1.2/TLSv1/g' /etc/ssl/openssl.cnf`
e
`sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/' /etc/ssl/openssl.cnf`

No docker é so rodar esses comando utilizando o `RUN`

Referencias:
[Link1](https://github.com/dotnet/runtime/issues/30667)
[Link2](https://stackoverflow.com/questions/36417224/openssl-dh-key-too-small-error)
[Link3](https://github.com/dotnet/dotnet-docker/issues/1109)
[Link4](https://medium.com/@edgar/how-to-resolve-openssl-sslv3-alert-handshake-failures-ruby-2-6-3-buster-cbc594537e7e)

@rftd não precisou do código da modificação. Funcionou no código atual da master 👍 .

Obrigado pela ajuda :D

**Comment by danilobreda** [comment]
Também verifiquei que com o .NET 5 algumas coisas vão mudar... [segue link.](https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux)
