### ISSUE TITLE
NFSE Itajai - qual provedor devo utilizar? o arquivo de municipios não tem Itajai - SC

### ISSUE THREAD

**Issue by FernandoARamos** [ACBrNet/ACBr.Net.NFSe#127]
NFSE Itajai - qual provedor devo utilizar? o arquivo de municipios não tem Itajai - SC.

Qual deve ser o provedor escolhido para gerar nfses para Itajai? Eu vi que existe o schemma do provedor Publica, porém não existe  o provedor publica no enum, e nem no arquivo de municipios está incluso Itajai.

Se puderem me indicar o caminho para a configuração para Itajai agradeço.

Att,

Fernando

**Comment by rftd** [comment]
Quem define o provedor é a prefeitura da sua cidade, se o provedor dela é este publica então não temos ele implementado.
Você precisa implementar ele se quiser usar.

**Comment by FernandoARamos** [comment]
Rafael,

Obrigado pela resposta. Fiquei em duvida pois vi vários threads ref a acbr.net usado Itajai, e na pasta schemas do projeto existe este provedor publica.

Sabe me dizer como o pessoal tem usado para Itajai?

**Comment by rftd** [comment]
Você pode esta confundindo com o projeto em Delphi lá tem este provedor, ou alguém implementou mais não fez um pull request.

**Comment by rftd** [comment]
Fechando issue por falta de retorno do usuário.
