### ISSUE TITLE
Ginfes Erro no formato XML

### ISSUE THREAD

**Issue by CarlosSantosJr** [ACBrNet/ACBr.Net.NFSe#130]
`        public string ConsultarNFSe(string cabecalho, string dados)
        {
            var message = new StringBuilder();
            message.Append("<gin:ConsultarNfseV3>");
            message.Append("<arg0>");
            message.AppendEnvio(cabecalho);
            message.Append("</arg0>");
            message.Append("<arg1>");
            message.AppendEnvio(dados);
            message.Append("</arg1>");
            message.Append("</gin:ConsultarNfseV3Response>");
            return Execute(message.ToString(), "RecepcionarLoteRpsV3Response");
        }`

A tag ConsultaNFfseV3 está com final diferente

**Comment by rftd** [comment]
Correçao já enviada.
