### ISSUE TITLE
Erro ao carregar o arquivo de municipios

### ISSUE THREAD

**Issue by ThalisonSantos** [ACBrNet/ACBr.Net.NFSe#136]
quando tento carregar o arquivo gera esse erro, Valor 'CancelaNFSe' solicitado não foi encontrado.

**Comment by ThalisonSantos** [comment]
tinha dois arquivos de municípios um funciona e outro não

**Comment by rftd** [comment]
o que não funciona esta faltando tags no xml por isso o erro.

**Comment by ThalisonSantos** [comment]
@rftd aproveitando estou encontrando outro erro 'O valor de enum inválido 'Conam' não pode ser desserializado no tipo 'ACBr.Net.NFSe.Providers.NFSeProvider'. Verifique se os valores de enum necessários estão presentes e marcados com o atributo EnumMemberAttribute se o tipo tiver o atributo DataContractAttribute.'

**Comment by rftd** [comment]
Verifique se esta atualizado sua versão do projeto pois aqui eu não consegui reproduzir o erro
