### ISSUE TITLE
Compatibilidade com VB6

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#14]
Gostaria de saber se essa DLL é compatível com VB6?

**Comment by rftd** [comment]
Os ajustes que estão sendo feito em COM Interop é para testar o funcionamento em linguagens que usem Activex.
Se quiser pode ir testando lembrando que apenas o Ginfes e o DSF estão implementados.

**Comment by leandrossantos** [comment]
@rftd quando compila a DLL ela gera o arquivo tlb para eu referenciar no VB6 ??

**Comment by rftd** [comment]
Se usar a configuração de compilação COM Interop ele gera.

**Comment by leandrossantos** [comment]
@rftd  essa da imagem abaixo?
[http://prntscr.com/cjwfri](http://prntscr.com/cjwfri)

**Comment by leandrossantos** [comment]
@rftd  e a DLL de SAT também é só marcar para gerar a TLB, ou precisa mexer ai ainda para eu conseguir usar no VB6 ?

**Comment by rftd** [comment]
Na dll do SAT ainda não foi feito as adaptações para COM Interop.

**Comment by leandrossantos** [comment]
@rftd  tem previsão da a DLL de SAT, estou com 3 projetos em VB6 que preciso implementar.

**Comment by leandrossantos** [comment]
@rftd tentei usar a compilação COM Interop para usar a DLL de NFSe em VB6 mais não consegui.
