### ISSUE TITLE
Versão de mensagem não reconhecida no teste c/ ISSe

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#144]
Boa tarde,
Estou tentando implementar o envio síncrono para o provedor ISSe, mas aparece "Versão de mensagem não reconhecida"

![image](https://user-images.githubusercontent.com/4941173/113024814-9142eb00-915d-11eb-8257-fa4837fd7bff.png)

Utilizei os dados abaixo para teste:

![image](https://user-images.githubusercontent.com/4941173/113025701-9fddd200-915e-11eb-9a2c-1aeab35579c0.png)

Alguém pode me dar uma luz sobre o que estou fazendo de errado ?

**Comment by rftd** [comment]
Primeira coisa que tem que checar é a versão abrsaf que o provedor utiliza depois quais serviços o provedor implementa, eu uso o SOAPUI para isso.
No SOAPUI tu consegue fazer os testes basicos de envio e retorno e com isso da para ajustar o xml gerado de acordo com o provedor

**Comment by Transis-Felipe** [comment]
A versão é a 2.01, mas o SOAPUI não reconhece o endereço do webservice como válido (ou eu não soube usar)

![image](https://user-images.githubusercontent.com/4941173/113043000-3d8ecc80-9172-11eb-9452-ebde84370a65.png)

![image](https://user-images.githubusercontent.com/4941173/113043022-467f9e00-9172-11eb-87d6-e5cddf154b3e.png)

**Comment by rftd** [comment]
tentou colocar ?wsdl no final da url, tem servidor que não faz isso quando é feito um get

**Comment by Transis-Felipe** [comment]
Sim, tentei https://nfse-ws.ecity.maringa.pr.gov.br/v2.01/?wsdl
Já fui inclusive nos nossos amigos do Acbr pra ver se descobria algo pela implentação deles
https://github.com/frones/ACBr/blob/master/Exemplos/ACBrDFe/ACBrNFSe/ArqINI/ISSe.ini

**Comment by rftd** [comment]
Use este endereço
https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01/?wsdl

**Comment by Transis-Felipe** [comment]
Eu já tinha tentado... :-(

![image](https://user-images.githubusercontent.com/4941173/113143514-98700480-9202-11eb-83db-86572bf5f56e.png)

![image](https://user-images.githubusercontent.com/4941173/113143528-9e65e580-9202-11eb-96ef-f58fbfd59c27.png)

**Comment by Transis-Felipe** [comment]
Eu vi o pessoal falando no ACBR que precisa usar opção de segurança TSL 1.2

Nós temos como escolher o tipo de TSL no projeto ?

**Comment by rftd** [comment]
Aqui funcionou no SOAPUI, sim tem TLS 1.2 no projeto.
Eu anexei o projeto aqui.
[Maringa-soapui-project.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/6237831/Maringa-soapui-project.zip)

**Comment by Transis-Felipe** [comment]
Segui a dica do SOAPUI e agora parei no erro: "'v2' é um prefixo não declarado. Linha 1, posição 107."

            var message = new StringBuilder();
            message.Append("<v2:EnviarLoteRpsSincrono soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">");
            message.Append("<xml xsi:type=\"xsd: string\">");
            message.AppendCData(msg);
            message.Append("</xml>");
            message.Append("</v2:EnviarLoteRpsSincrono>");

            const string SoapAction = "https://nfse-ws.ecity.maringa.pr.gov.br/v2.01#EnviarLoteRpsSincrono";

Está dando erro no WriteSoapEnvelope ao executar o Message.CreateMessage

![image](https://user-images.githubusercontent.com/4941173/113193759-b8b9b680-9236-11eb-9619-5d7c0e715cde.png)

**Comment by rftd** [comment]
você não passou o namespace mais colocou um prefixo por isso o erro
v2 ali é um prefixo que deve estar no pacote soap

xmlns:v2="https://nfse-ws.hom-ecity.maringa.pr.gov.br/v2.01"

passa este namespace no metodo executar que este erro sai
outra coisa lai não é CData se o tipo é string não é CData o append, use AppendEnvio

**Comment by Transis-Felipe** [comment]
Oi @rftd primeiramente gostaria de agradecer as dicas, fico muito feliz.

Estamos progredindo. Olha como ficou:

```
            var message = new StringBuilder();
            message.Append("<v2:EnviarLoteRpsSincrono soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">");
            message.Append("<xml xsi:type=\"xsd: string\">");
            message.AppendEnvio(msg);
            message.Append("</xml>");
            message.Append("</v2:EnviarLoteRpsSincrono>");
```
Agora, estou trancado no erro abaixo, ao chamar o Channel.Request:
"O tipo de conteúdo text/xml;charset=UTF-8 da mensagem de resposta não corresponde ao tipo de conteúdo da associação (application/soap+xml; charset=utf-8)"

![image](https://user-images.githubusercontent.com/4941173/113296175-814b1880-92cf-11eb-84eb-4d97efea293e.png)


Exemplo da prefeitura:

![image](https://user-images.githubusercontent.com/4941173/113295797-07b32a80-92cf-11eb-81fb-ea5baf0e771a.png)

Nosso xml:

![image](https://user-images.githubusercontent.com/4941173/113295841-17327380-92cf-11eb-80d6-9c2f53490018.png)

**Comment by rftd** [comment]
Este erro é que tu ta mandando Soap11 e deve estar usando soap12

**Comment by Transis-Felipe** [comment]
Eu estou mandando soap 12

 `   internal sealed class ISSeServiceClient : NFSeSOAP12ServiceClient, IServiceClient`

Tu quis dizer que eu estou misturando os dois tipos de soap, ou que eu deveria usar soap 12 ao invés de 11?
   
Vou procurar onde eu escolho o tipo de soap, no momento do envio...

**Comment by rftd** [comment]
Desculpa escrevi errado maringa usa Soap11 e não 1.2

**Comment by Transis-Felipe** [comment]
Pelo SOAPUI, diz que eles usam 1.2. Onde tu viu que é 1.1 ?

![image](https://user-images.githubusercontent.com/4941173/114024335-4e160580-984a-11eb-85b8-53ff0530a8f5.png)

**Comment by rftd** [comment]
Aqui esta como 1.1 e funciona a comunicação.
![Sem título](https://user-images.githubusercontent.com/299476/114940267-949dce00-9e0f-11eb-9477-4f373dfd9bf4.png)

**Comment by Transis-Felipe** [comment]
Se eu trocar para soap 1.1 ele volta ao primeiro erro desse chamado. "Versão de mensagem não reconhecida"

![image](https://user-images.githubusercontent.com/4941173/113024814-9142eb00-915d-11eb-8257-fa4837fd7bff.png)

**Comment by rftd** [comment]
Eu adicionei o servidor ISSe favor fazer testes com o mesmo.

**Comment by Transis-Felipe** [comment]
Testei e deu o mesmo problema da minha implementação: "Versão de mensagem não reconhecida"

![image](https://user-images.githubusercontent.com/4941173/115275852-b4d3d280-a118-11eb-9fca-507f73f4860b.png)

**Comment by rftd** [comment]
Pelo que pude apurar é um erro ao processar a menssagem de retorno do webservice do ISSe, ela não vem no padrão esperado pelo conversor em .net.
Ai complica a vida da pessoa, kkkkkkkkkkkkkkkkk

**Comment by Transis-Felipe** [comment]
O pior ainda é que essa tranqueira de provedor só tem em uma cidade

**Comment by rftd** [comment]
Tem como contornar e fazer o processo de forma manual, mas é chato depois eu vejo aqui

**Comment by Transis-Pedro** [comment]
Tem algum provedor que isso já foi feito ou precisa ser feito novo ?

**Comment by rftd** [comment]
Não foi feito ainda, precisa ser feito manualmente as coisas e no momento to sem vontade de fazer.

**Comment by Transis-Felipe** [comment]
> Não foi feito ainda, precisa ser feito manualmente as coisas e no momento to sem vontade de fazer.

E se pagar, a vontade volta? Heheh 😁😁😁

**Comment by rftd** [comment]
Esta semana foi a semana do meu aniversario então to pegando ligth, semana que vem eu vou voltar nas coisas.
Agora se quiser ajudar o projeto basta ir no padrin ou apoia-se e contribuir.

**Comment by Transis-Felipe** [comment]
> Esta semana foi a semana do meu aniversario então to pegando ligth, semana que vem eu vou voltar nas coisas.
> Agora se quiser ajudar o projeto basta ir no padrin ou apoia-se e contribuir.

Opa! Parabéns!

Eu já faço doação mensal, faz mais de um ano, no apoia-se. 
Mas se tu quiser cobrar algo mais, para acelerar esse provedor, diga aí, que eu vejo se consigo.

Abraço

**Comment by Transis-Felipe** [comment]
Oi @rftd eu sei que doação em dinheiro tb dá pra comprar qualquer coisa, mas as vezes um produto físico é mais representativo. 
Por exemplo: compra algo no kabum e me manda o boleto, que eu pago pra ti. 
Se entra em dinheiro digital as vezes nem vemos e ele já se vai.

**Comment by rftd** [comment]
Mano eu to terminando algo aqui que outro apoiador pediu, assim que terminar vou olhar este problema aqui.
Sobre o produto mano se eu escolher algo que preciso do Kabum tu vai entrar em depressão.
kkkkkkkkkkkkkkkkkkkkkkkkkk

**Comment by rftd** [comment]
Desculpa a demora, mas na próxima semana devo começar a mexer nesta issue.

**Comment by rftd** [comment]
![Sem título](https://user-images.githubusercontent.com/299476/120094348-d2b82e00-c0ed-11eb-9b95-8e2cbc7cd3a0.png)
Consulta já funcionando.

**Comment by rftd** [comment]
![Sem título](https://user-images.githubusercontent.com/299476/120094406-20cd3180-c0ee-11eb-86c7-e1acf6b75e8c.png)
Consulta funcionando.

**Comment by rftd** [comment]
Já enviei as modificações se puder terminar de fazer os testes eu agradeço.

**Comment by rftd** [comment]
E descobri o motivo do erro, é que o webservice se colocar ?wsdl na url mesmo fazendo um post ele responde igual o get e tras o wsdl, por isso dava este erro olha que lindo.
Basicamente se coloca-se a url sem ?wsdl teria funcionado desdo começo.

**Comment by Transis-Felipe** [comment]
Oi Rafael,

Está retornando o erro abaixo quando tento fazer o envio. 
Tu passou pela parte de envio e deu problema na consulta de lote por causa do usuário sem autorização ?

![image](https://user-images.githubusercontent.com/4941173/120241305-dad0b480-c238-11eb-9e7c-1ac29b0233f9.png)

Vou continuar investigando...

**Comment by Transis-Felipe** [comment]
Temos 2 assinaturas no xml, enquanto o modelo da prefeitura exige 1.

![image](https://user-images.githubusercontent.com/4941173/120241926-233ca200-c23a-11eb-98d8-11a0f6147241.png)

Vou fazer um Override na assinatura e depois posto se funcionou.
```
        protected override void AssinarEnviarSincrono(RetornoEnviar retornoWebservice)
        {

        }
```

**Comment by rftd** [comment]
nesse caso já outro problema então abrimos outra issue para não misturar os assuntos

**Comment by Transis-Felipe** [comment]
Corrigi aquele erro com o override. Vou mandar o PR
