### ISSUE TITLE
BHISS - The 'http://www.w3.org/2000/09/xmldsig#:Signature' element is not declared.

### ISSUE THREAD

**Issue by hgmauri** [ACBrNet/ACBr.Net.NFSe#145]
Boa tarde

Estou utilizando o package ACBr.Net.NFSe versão 1.5.1.1 no .NET e estou recendo o seguinte erro tentando registrar nota utilizando o BHISS:

`The 'http://www.w3.org/2000/09/xmldsig#:Signature' element is not declared.`

A configuração que utilizo é:

`            acbrNFSe = new ACBrNFSe();

            acbrNFSe.Configuracoes.Geral.Salvar = true;
            acbrNFSe.Configuracoes.Arquivos.Salvar = true;
            acbrNFSe.Configuracoes.Arquivos.PathSchemas = $"{Directory.GetCurrentDirectory()}" + @"\Schemas";

            acbrNFSe.Configuracoes.WebServices.Ambiente = checkEnvironment.IsProduction() ? DFeTipoAmbiente.Producao : DFeTipoAmbiente.Homologacao;
            acbrNFSe.Configuracoes.WebServices.CodigoMunicipio = 3106200;

            acbrNFSe.Configuracoes.Certificados.Certificado = $"{Directory.GetCurrentDirectory()}" + @"\Certificados\BH\cert.pfx";
            acbrNFSe.Configuracoes.Certificados.Senha = "123456";

            acbrNFSe.Configuracoes.PrestadorPadrao.CpfCnpj = "{CNPJ da empresa}";
            acbrNFSe.Configuracoes.PrestadorPadrao.InscricaoMunicipal = "{Inscrição da empresa}";
            acbrNFSe.Configuracoes.PrestadorPadrao.Endereco.CodigoMunicipio = 3106200;
            acbrNFSe.Configuracoes.PrestadorPadrao.Endereco.Uf = "MG";`

Podem me ajudar com esse erro? Já tentamos várias configurações

**Comment by rftd** [comment]
Qual o ambiente que esta testando ??
Pois acabei de testar aqui e foi gerado e enviado corretamente, no windows, se tiver usando linux tem que fazer configurações para criptografia funcionar direito

**Comment by rftd** [comment]
A Assinatura do rps e do lote ocorre na linha 1170 da classe ProviderABRASF.

**Comment by hgmauri** [comment]
@rftd estamos testando em ambiente de homologação.
O teste que estamos realizando é um teste local, rodado no sistema Windows, e o erro persiste.

Você tem algum exemplo de utilização chamando o BHISS? Ou passar como posso preencher correto a assinatura nos campos abaixo?

`nota.Signature.KeyInfo = new KeyInfo();
nota.Signature.SignatureValue = "";`

**Comment by rftd** [comment]
Não precisa preencher a parte de assinatura, isso será preenchido na hora de assinar o xml e isto ocorre antes do envio
Todos os testes que faço eu uso o demo que esta no repositorio

**Comment by hgmauri** [comment]
Estamos utilizando o Azure Functions .NET Core 3.1, teria que mudar algo pra funcionar? mesmo assim o erro persiste.

**Comment by rftd** [comment]
O erro é claro não esta conseguindo assinar por isso que esta reclamando da falta da assinatura, pelo visto a parte de criptografia não funciona corretamente ai, o jeito é entrar em contato com eles e ver o que pode ser.

**Comment by viniciuscluna** [comment]
Boa tarde, 
Estou enfrentando o mesmo problema, ao que me parece é alguma incompatibilidade com Net Core.
Fiz duas aplicações Console (Uma em .NET 4.7, outra em .NET Core 3.1) com o mesmo código, 
Na versão .NET 4.7 A pasta Schemas é criada automaticamente, .NET Core não, configurando manualmente a localização da pasta (Configuracoes.Arquivos.PathSchemas) o projeto aceita.
![image](https://user-images.githubusercontent.com/36234150/113040453-2bf7f580-916f-11eb-834c-120adc08d315.png)



            var _teste = new ACBrNFSe();

            //Salvar os arquivos
            _teste.Configuracoes.Geral.Salvar = true;
            _teste.Configuracoes.Arquivos.Salvar = true;



            //webservices
            //Configure os dados da cidade e do Certificado aqui
            _teste.Configuracoes.WebServices.Ambiente = DFeTipoAmbiente.Homologacao;
            _teste.Configuracoes.WebServices.CodigoMunicipio = 3106200;


            _teste.Configuracoes.Arquivos.PathSchemas = @"C:\Schemas\";
            _teste.Configuracoes.Certificados.Certificado = @"C:\Users\Vinicius\Downloads\CERT.pfx";
            _teste.Configuracoes.Certificados.Senha = "senha";



            _teste.Configuracoes.PrestadorPadrao.CpfCnpj = "CNPJ";
            _teste.Configuracoes.PrestadorPadrao.InscricaoMunicipal = "IM";
            _teste.Configuracoes.PrestadorPadrao.Endereco.CodigoMunicipio = 3106200;
            _teste.Configuracoes.PrestadorPadrao.Endereco.Uf = "MG";


            //adicionado rps
            var nota = _teste.NotasServico.AddNew();
            nota.Prestador.CpfCnpj = "CNPJ";
            nota.RegimeEspecialTributacao = RegimeEspecialTributacao.SimplesNacional;
            nota.Servico.Valores.Aliquota = 2;
            nota.Servico.CodigoTributacaoMunicipio = "802";
            nota.NaturezaOperacao = NaturezaOperacao.Sigiss.TributadaNoPrestador;
            nota.Servico.Valores.ValorServicos = 29.91M;
            nota.Servico.Valores.BaseCalculo = 29.91M;
            nota.Servico.Descricao = "serviço teste";
            nota.Tomador.Tipo = TipoTomador.Sigiss.PFNI;
            nota.Tomador.DadosContato.Email = "teste@gmail.com";
            nota.Tomador.CpfCnpj = "CNPJ";



            nota.IdentificacaoRps.Numero = $"1234456";
            nota.IdentificacaoNFSe.Numero = $"12345667";
            nota.IdentificacaoRps.Serie = "223";
            nota.IdentificacaoRps.Numero = "1234456";
            nota.IdentificacaoRps.DataEmissao = DateTime.Now;



            nota.Servico.Valores.Aliquota = 1;
            nota.Servico.Valores.AliquotaCargaTributaria = 1;
            nota.Servico.Valores.AliquotaCofins = 1;
            nota.Servico.Valores.AliquotaIR = 1;
            nota.Servico.Valores.AliquotaInss = 1;
            nota.Servico.Valores.AliquotaPis = 1;
            nota.Servico.ItemListaServico = "1005";



            nota.Servico.Discriminacao = "PROCESSO REF: |";

            var retorno = _teste.Enviar(1);


Retorno em Net 4.7:
![image](https://user-images.githubusercontent.com/36234150/113041195-0f0ff200-9170-11eb-95b0-e7a6bb80e21f.png)

Retorno em Net Core:
![image](https://user-images.githubusercontent.com/36234150/113041280-2949d000-9170-11eb-9545-5dd79d355c8f.png)

**Comment by rftd** [comment]
Eu fiz teste aqui na versão 3.1 do .net core o erro não á na assinatura o xml esta assinado corretamente, mas mesmo assim o validador de schema diz que não, deve ser algum erro nesta parte do .net core, eu vou ter que investigar para saber como resolver

**Comment by viniciuscluna** [comment]
Estou verificando a biblioteca do seu projeto e forçando o Net Core para tentar descobrir no código o erro, creio que o problema esteja relacionado a isso:
https://github.com/dotnet/runtime/issues/29346

**Comment by rftd** [comment]
Pelo que li no forum realmente tem erro nesta parte do .net core, vamos ver se conseguimos fazer algum workaround como sempre.
Na vdd não é erro, foi mudado o comportamento pelo visto no .net core por isso funciona diferente.

https://github.com/dotnet/runtime/issues/29346#issuecomment-485798826

**Comment by viniciuscluna** [comment]
Na classe XmlSchemaValidation.cs
![image](https://user-images.githubusercontent.com/36234150/113047281-809f6e80-9177-11eb-973e-e0edd7140c40.png)
 Esse ajuste resolveu o problema

**Comment by hgmauri** [comment]
Ótimo @viniciuscluna, fiz esse teste agora com o .NET Core 3.1 e funcionou tudo normalmente. 

Também foi preciso incluir o código abaixo na linha 117 em ACBrNFS.cs:
`ServicePointManager.SecurityProtocol = (SecurityProtocolType) 3072;`
Obrigado pelo apoio.

@rftd É possível incluir essa validação no projeto pra gerar uma nova versão do nuget? 
Muito obrigado

**Comment by rftd** [comment]
> Na classe XmlSchemaValidation.cs
> ![image](https://user-images.githubusercontent.com/36234150/113047281-809f6e80-9177-11eb-973e-e0edd7140c40.png)
> Esse ajuste resolveu o problema

Sim foi como eu falei no post acima, foi mudado o comportamento padrão e por isso agora é necessario colocar esta linha.

**Comment by viniciuscluna** [comment]
Verifiquei aqui no meu projeto que ao colocar essa linha antes de enviar o RPS o problema é resolvido:

![image](https://user-images.githubusercontent.com/36234150/113049457-0d4b2c00-917a-11eb-8588-eae0d8b07590.png)

Dessa forma não se faz necessário mexer na sua biblioteca.  
Muito obrigado pelo apoio @rftd

**Comment by rftd** [comment]
Sim isso tbm resolve, mas eu vou mudar lá assim resolve de uma vez.
