### ISSUE TITLE
BHISS - falta atributo versão no envio

### ISSUE THREAD

**Issue by viniciuscluna** [ACBrNet/ACBr.Net.NFSe#146]
Bom dia,
Estou realizando a integração com a prefeitura de BH para emitir NFse, estou utilizando a forma síncrona de emissão, após preencher os dados e enviar para a prefeitura, recebi o seguinte erro:
**_"The required attribute 'versao' is missing_**
![image](https://user-images.githubusercontent.com/36234150/113146053-978ca200-9205-11eb-96af-5cb97836ceb7.png)

Ao olhar o xml enviado, verifiquei que o mesmo encontra sem o atributo versão no lote do xml:
![image](https://user-images.githubusercontent.com/36234150/113146349-ee927700-9205-11eb-8c46-0b28fe9acbdf.png)
Para a prefeitura aceitar, o modelo deveria estar com esse atributo:
![image](https://user-images.githubusercontent.com/36234150/113146458-141f8080-9206-11eb-8520-d8b4dce6a9fe.png)

Verificando na implementação do código, o BHISS chama o provider ABRASF que não seta o atributo versão:
![image](https://user-images.githubusercontent.com/36234150/113146838-885a2400-9206-11eb-86a5-a1f5ecd26cc2.png)

Poderia me informar como resolvo o problema caso seja falta de algum preenchimento na nota, ou se se trata realmente de problema na emissão

Obrigado!

**Comment by rftd** [comment]
como sempre cada local segue o padrão da forma que quer temos algumas opções para isso.

1. Sobre escrever o metodo na classe BHISS
2. Criar um metodo igual o GetNameSpace.
3. Criar uma propriedade interna que colocar ou não o attributo.

Eu preferencialmente gosto mais da opção 2.

**Comment by viniciuscluna** [comment]
Creio que a segunda opção faz mais sentido também, testei aqui e é somente essa a divergência na hora de comunicar com a prefeitura, de resto o Rps é enviado

**Comment by viniciuscluna** [comment]
Creio que o ajuste deve ser visto também para a função assíncrona, essa não testei mas acho que pode dar problema também.

**Comment by rftd** [comment]
Não sei pois o GerarNFSeEnvio não faz parte do padrão ABRSAfV1 e sim da V2 alguns provedores que resolveram implementar algo semelhante na V1.

**Comment by viniciuscluna** [comment]
Entendi, creio então que seja somente o síncrono no momento, muito obrigado @rftd pelo suporte

**Comment by Transis-Felipe** [comment]
@viniciuscluna deu certo?

**Comment by viniciuscluna** [comment]
Bom dia, após inserir o atributo versão a comunicação funcionou corretamente.
Criei um projeto e converti para Net Core e a partir dele estou realizando ajustes para a emissão de NF de diferentes prefeituras para uso interno.
Obrigado pelo suporte de todos.

**Comment by rftd** [comment]
Não precisa mudar o projeto para .net core ele tem versão .net standard basta criar um demo ou consumir a dll direto em um projeto .net core.
