### ISSUE TITLE
Could not load file or assembly 'System.ServiceModel.Primitives' ao emitir nota e cancelamento

### ISSUE THREAD

**Issue by danilobreda** [ACBrNet/ACBr.Net.NFSe#147]
Aconteceu o seguinte erro em ambiente linux usando .net 5:
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. 

Versão: ultima conferida no dia 01/04/2021 as 18:41

**Comment by rftd** [comment]
Faltou esta dll System.ServiceModel.Primitives confere se a mesma se encontra junto das dlls.

**Comment by danilobreda** [comment]
Vi que o nuget está o 4.7
e o erro é do 4.8 será que é isso?
![image](https://user-images.githubusercontent.com/14843499/113357678-c0eb2200-931a-11eb-8382-fa82d9487493.png)

**Comment by rftd** [comment]
então o que pode estar usando esta assembly pode ser outra parte do software e não a minha dll em si
cheque todas as referencias de todas as assemblys do seu software

**Comment by danilobreda** [comment]
Resolvi instalando os pacotes system.servicemodel.http e primitives manualmente nos projetos.

Eu gero meus nugets internos de forma automatizada referenciando o acbr, só adicionei os 2 no mesmo.
