### ISSUE TITLE
Novos Servidores

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.NFSe#15]
Boa noite @rftd,

Tentei entender um pouco o fonte, mas não ficou claro para mim... o que deveria ser feito para implementar um novo servidor?

**Comment by rafd75** [comment]
@marcosgerene - boa tarde...

Desculpe a demora na resposta. Eu fiz o GINFES com a ajuda do Rafael. Mas quem começou e preparou a base desse provedor foi o Rafael. Eu implementei as funções... Apanhei um pouco, mas acabou saindo.

Desde outubro estou usando o GINFES em produção (Ribeirão Preto) e hoje fiz a primeira emissão também na cidade de São Carlos. Parece que está tudo ok.

Tenho 3 pendências para resolver ainda no projeto, espero estar com tudo ok até o final da próxima semana.

Em seguida, vou precisar implementar o provedor da NF Paulistana. Comentei com o Rafael que eu gostaria de fazer desde o princípio. Se isso realmente ocorrer, vou documentar (passo a passo) o que eu for fazendo, para incluir isso na documentação do projeto e facilitar a vida de quem quiser implementar novos provedores...

Espero estar com esse provedor implementado (e em produção) ainda este ano...

Qual provedor você tem necessidade de implementar?

**Comment by leandrossantos** [comment]
@rafd75  estou precisando dos provedores: Agili, FissLex e Pronim/Dueto você consegue ver esses provedores também?

**Comment by rafd75** [comment]
Leandro... na minha lista, está o NF Paulista e depois Thema (só para 2017).

O que eu vou fazer, é criar um passo a passo, para facilitar a implantação de novos provedores por outros desenvolvedores.

Minha dificuldade inicial foi exatamente essa... não entender como começar um novo provedor.

O Ginfes, eu fiz metade apenas (o Rafael que fez as interfaces, etc.)... É isso que eu quero documentar desde o principio... e assim, espero que outros provedores vão surgir...

**Comment by leandrossantos** [comment]
@rafd75 tendo uma documentação bem detalhada de cada procedimento que temos que fazer para implementar novos provedores poderemos ajudar também.

**Comment by rftd** [comment]
https://github.com/ACBrNet/ACBr.Net.NFSe/wiki/Adicionando-um-novo-servidor

**Comment by marcosgerene** [comment]
@rafd75 

No momento estou focado no CTe, que no meu caso já está com o prazo apertado, assim que possível quero implementar o SimplISS

**Comment by leandrossantos** [comment]
@marcosgerene o seu CTe você esta fazendo mo mesmo padrão da Zeus NFe ???

**Comment by marcosgerene** [comment]
@leandrossantos 
Não, na verdade estou desenhando no meu sistema mesmo, eu ia usar o ACBRPlus para o CTE, mas parece que o @rftd vai liberar em breve o CTe do ACBr, então estou segurando um pouco para usar o dele, se tiver a mesma qualidade do ACBrSAT vai ser fenomenal =D

**Comment by leandrossantos** [comment]
Alguma previsão de liberar para o provedor WebISS ???

**Comment by rafd75** [comment]
@leandrossantos - Meu próximo servidor será a NFSe Paulistana (cliente aguardando essa solução). E na sequencia, Thema (neste caso, o cliente já está operacional com a solução da FlexDocs, então não tenho pressa, mas vou fazer para deixar apenas uma solução gerenciando as NFSe do nosso sistema).

Sugiro que você leia o link a seguira para que você mesmo implemente os provedores que você está precisando: https://github.com/ACBrNet/ACBr.Net.NFSe/wiki/Adicionando-um-novo-servidor

**Comment by RBACORP** [comment]
@rftd Boa Tarde.... 
Estou Migrando agora para o C#. A maioria dos meus projetos são em VB6. Tentei Acessar os Métodos da Dll usando earling binding ou Late binding e Não obtive Sucesso. Notei que o COM Interop estava desmarcado, mas mesmo habilitando não consigo Acessar os Métodos. Eu também uso a Dll da FlexDocs  , tem alguma forma de usar a dll do ACBR assim como usamos a da FlexDocs?
Obrigado

**Comment by rafd75** [comment]
@RBACORP , boa tarde.

Eu trabalho com VFP (acredito que seja a mesma coisa que VB6)... e uso a DLL assim:

oNFSe = CreateObject("AcbrNfseProxy")

E depois, eu consumo os métodos da classe ACBrNFSeProxy.cs.

Por exemplo:

Store "" To m.msgAvisos, m.msgErros
retorno = oNFE.SetupWebService(CodCidade, 2, "Certificado", "Senha", @m.msgAvisos, @m.msgErros)

if retorno=.F.
    MessageBox(msgErros)
endIf


--- desculpe a pressa na resposta, mas por ai, acho que já da para você verificar se funciona do mesmo jeito no VB6.

Com relação ao COM Interop, o @rftd pode te explicar o motivo de termos abandonado essa implantação... Ocorreram alguns erros, que não ocorriam nas outras formas de compilar a DLL.

OBS: No caso do VFP, eu sou obrigado a colocar a DLL na mesma pasta do EXECUTAVEL da aplicação. Além disso, é necessário registrar a DLL no windows (REGASM)... 

Faça um teste e retorne se conseguiu utilizar....

Aqui, estou usando dessa forma, em produção (GINFES) nos municipios de Ribeirao Preto/SP e Sao Carlos/SP. 100% funcional!

abs!

**Comment by RBACORP** [comment]
@rafd75  Entendi... Estava fazendo dessa forma, porem não tinha conseguido registrar a dll. Agora Consegui Acessar os Métodos. Outra Dúvida.. Vou emitir Nota para a cidade de São José do Rio Preto, que no caso também usa a (GINFES). Preciso Acrescentar a Cidade em Algum lugar ou Não?.

Abraço!

**Comment by rafd75** [comment]
@RBACORP - bom dia! ... 

Eu acabei de adicionar os dados para São José do Rio Preto, já está disponível para download...... Verifique se deu certo.

**Comment by RBACORP** [comment]
@rafd75 Cara Deu certo Sim... O erro de Cidade não Cadastrada parou de Acontecer... Vc disse que está usando em Produção já em duas cidades, teria como vc me passar a sequencia exata que tenho que fazer para conseguir emitir ou consultar uma NFS-e?  Estou um pouco perdido rsrsrsrsrs

**Comment by rafd75** [comment]
Ta na mão:

https://github.com/ACBrNet/ACBr.Net.NFSe/wiki/Exemplo-de-Uso-da-DLL-usando-a-classe-Proxy

**Comment by RBACORP** [comment]
@rafd75 Obrigado!! Funcionou quase 100%. Só não consigo consumir o Método RPSValores.
Sabe me dizer o porque??
Abraço!

**Comment by rafd75** [comment]
Me passa o código que vc está usando... e qual a mensagem de erro...

**Comment by RBACORP** [comment]
Nos outros métodos ele me mostra os parametros nesse em especifico não...
Estou usando da Seguinte forma:
 ret = oNFSe.RPSValores(10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 2, 0, 0, 0, 0, 0, msgAlerta, msgErro)
Ele me retorna a seguinte mensagem:
Function or interface marked as restricted, or the function uses an Automation type not supported in Visual Basic

**Comment by rftd** [comment]
Isto é provavelmente por causa do decimal mas tarde eu vou fazer uma modificação pois o VB6 não usa decimal e sim Currency

**Comment by rafd75** [comment]
@RBACORP - o @rftd atualizou o código da classe Proxy... Atualiza e testa ai... Se der certo, depois eu vou testar aqui (Visual FoxPro).;

**Comment by RBACORP** [comment]
@rftd e @rafd75  Galera... Consegui acessar as propriedades agora... Porem quando vou consumir o método o vb trava e fecha... 
Oque eu já tentei:
Estava colocando valores diretos nas propriedades ex: oNfse.RPSValores(10,0,0,0...) dava erro de referencia ao objeto.
Criei as variaveis do tipo currency e atribui os valores a elas ex: Dim vlr as Currency  vlr = "10.00" oNfse.RPSValores(vlr,0,0,0...) Nesse caso VB trava e fecha.

Tentei alterar no C# de Decimal para Double mas não obtive sucesso.
Ps: Tentei os valores com (10.00 e 10,00)
Abraço

**Comment by rafd75** [comment]
@RBACORP , bom dia!

Infelizmente eu não vou conseguir te ajudar com isso. Pelo que o @rftd comentou, existe alguma incompatibilidade do VB com o tipo Decimal do C#...

Nunca utilizei o VB. No meu caso, eu uso o Visual FoxPro, que está funcionando normalmente com esse método... Você comentou que utiliza com o FlexDocs, mas neste caso, eu não me recordo de nenhum método deles que receba um decimal... Acho que será necessário fazer alguma pesquisa para entender melhor como funciona essa integração do C# com o VB...

Obs: após a alteração que o @rftd fez no código da função RPSValores, eu não testei no VFP ainda (não posso te afirmar que com essa alteração, aqui continua funcionando... deixei para fazer isso na hora que você confirmasse que no VB havia funcionado...)

**Comment by RBACORP** [comment]
@rafd75 Tranquilo já me ajudaram bastante Obrigado.... Vou ver oque descubro sobre essa incompatibilidade... Acho que a FlexDocs passou pelo mesmo problema... pois eles não tem nenhum método que use o decimal, eles apenas pegam o loteRPS gerado em txt convertem em XML e fazem o envio, com isso eles não precisam tratar os valores... Acho que essa foi a Saída que eles encontraram...
Vou Pesquisar Sobre, e os mantenho informados para colaborar com o projeto 
Abraços!

**Comment by rafd75** [comment]
@RBACORP , o @rftd adicionou um novo projeto que é quase igual a classe Proxy que você está usando, com a diferença de ter 2 métodos:

ClearNotas
AddNotas

Sendo que AddNotas aceita um json para incluir os RPSs na coleção.

Os demais métodos, são os mesmos que você já tem no exemplo (Enviar, etc)...

Como exemplo de json:

{
   "Id" : 0,
   "Prestador" : {
      "CpfCnpj" : "01001001000101",
      "InscricaoMunicipal" : "12345",
      "Senha" : "",
      "FraseSecreta" : "",
      "ChaveAcesso" : null,
      "RazaoSocial" : null,
      "NomeFantasia" : null
   },
   "NaturezaOperacao" : "NT01",
   "RegimeEspecialTributacao" : "Nenhum",
   "DataOptanteSimplesNacional" : "0001-01-01T03:00:00Z",
   "IncentivadorCultural" : "Nao",
   "Producao" : "Sim",
   "Situacao" : "Normal",
   "DeducaoMateriais" : "Sim",
   "LocalServico" : "Tomador",
   "NumeroLote" : null,
   "Protocolo" : null,
   "Competencia" : "0001-01-01T03:00:00Z",
   "OutrasInformacoes" : null,
   "ValorCredito" : 0,
   "TipoEmissao" : "NormalNFSe",
   "EmpreitadaGlobal" : "ConstrucaoCivil",
   "TipoTributacao" : "Tributavel",
   "Assinatura" : null
}

Veja se agora da certo...

OBS: Você vai precisar registrar (RegAsm) esta DLL -> ACBr.Net.NFSe.Proxy.Json.dll

**Comment by rafd75** [comment]
Aproveitando: Acabei de testar no VFP o método RPSValores com a inclusão do [MarshalAs(UnmanagedType.Currency) ... foi transparente... tudo OK!

**Comment by rafd75** [comment]
@RBACORP --- conseguiu testar utilizando a classe JSON?

**Comment by RBACORP** [comment]
@rafd75 @rftd  Galera desculpa a Demora pra responder... estava enforcado em outro projeto...
Vamos lá.... @rafd75  Não testei usando a classe JSON...  fiz uma pequena POG (Programação Orientada a Gambiarra) para funcionar no vb6. Alterei os parametros do Método RPSValores para serem todos do tipo string, e dentro do método eu converto para decimal... Segue Abaixo o trecho do código que eu mudei.

  public bool RPSValores(string valorServicos, string valorDeducoes, string valorPis, string valorCofins, string valorInss, string valorIr, string valorCsll, string valorIss, string valorOutrasRetencoes,
                               string valorBaseCalculo, string aliquota, string valorLiquidoNFSe, string issRetido,
                               string valorIssRetido, string valorDescontoCondicionado, string valorDescontoIncondicionado,
                               string valorCredito, ref string mensagemAlerta, ref string mensagemErro)
        {
            try
            {
                NFSe.Servico.Valores.ValorServicos = Convert.ToDecimal(valorServicos);
                NFSe.Servico.Valores.ValorDeducoes = Convert.ToDecimal(valorDeducoes);
                NFSe.Servico.Valores.ValorPis = Convert.ToDecimal(valorPis);
                NFSe.Servico.Valores.ValorCofins = Convert.ToDecimal(valorCofins);
                NFSe.Servico.Valores.ValorInss = Convert.ToDecimal(valorInss);
                NFSe.Servico.Valores.ValorIr = Convert.ToDecimal(valorIr);
                NFSe.Servico.Valores.ValorCsll = Convert.ToDecimal(valorCsll);
                NFSe.Servico.Valores.IssRetido = (SituacaoTributaria)Convert.ToInt16(issRetido);
                NFSe.Servico.Valores.ValorIss = Convert.ToDecimal(valorIss);
                NFSe.Servico.Valores.ValorOutrasRetencoes = Convert.ToDecimal(valorOutrasRetencoes);
                NFSe.Servico.Valores.BaseCalculo = Convert.ToDecimal(valorBaseCalculo);
                NFSe.Servico.Valores.Aliquota = Convert.ToDecimal(aliquota);
                NFSe.Servico.Valores.ValorLiquidoNfse = Convert.ToDecimal(valorLiquidoNFSe);
                NFSe.Servico.Valores.ValorIssRetido = Convert.ToDecimal(valorIssRetido);
                NFSe.Servico.Valores.DescontoCondicionado = Convert.ToDecimal(valorDescontoCondicionado);
                NFSe.Servico.Valores.DescontoIncondicionado = Convert.ToDecimal(valorDescontoIncondicionado);
                NFSe.ValorCredito = Convert.ToDecimal(valorCredito);
            }
            catch (Exception ex)
            {
                while (ex != null)
                {
                    mensagemErro += ex.Message + Environment.NewLine;
                    ex = ex.InnerException;
                }
                return false;
            }
            return true;
        }

Agora vou começar os testes realmente.... As informações de retorno tal como, numero da nfse, codigo de verificação são todas retornadas no xmlRetorno?

Abraço e obrigado a Todos.

**Comment by RBACORP** [comment]
Boa Tarde a todos..... Consegui usar o Método RPSValores com [MarshalAs(UnmanagedType.Currency) .
Funciona Perfeitamente... era bug do meu VB mesmo....
Consegui emitir algumas notas em ambiente de teste, porem não consigo acessar os retornos do WebService, os Métodos:

'// Mensagem de Envio para o webservice
xmlSituacaoEnvio = oNFSE.MensagemRetorno.XmlEnvio
'// Mensagem de Retorno do webservice
xmlSituacaoRetorno = oNFSE.MensagemRetorno.XmlRetorno
'// Situacao do Lote
situacaoDoLote = oNFSE.MensagemRetorno.Situacao

o vb acusa que não existem  erro: Method or data member not found
e tbm não consegui cancelar as notas que eu emiti.... diz: Código de cancelamento incorreto
porem já usei todos os que encontrei e nada.... Alguem conseguiu cancelar usando o provedor GINFES? se sim qual o código utilizado....
Abraço a todos e Obrigado.

**Comment by rafd75** [comment]
Opa... legal sobre o MarshalAs().... um problema a menos

Com relação ao cancelamento, tente utilizar o código 0001 (zero zero zero um) - digita os zeros ai... veja se passa. Encontrei por acaso esse código, e não sei seu significado... 0002 não funciona. Parece que é obrigatório e só existe o 0001... coisas do GINFES.

Sobre a MensagemRetorno -> qual a linha em VB que está dando esse problema? É exatamente essa ai: oNFSE.MensagemRetorno.XmlRetorno ?

quando você digita oNFSE e o ponto (.), não abre o Intellisense do VB mostrando as propriedades?

**Comment by leandrossantos** [comment]
estou aqui na luta para implementar o provedor WebISS mais tá complicado.

**Comment by leandrossantos** [comment]
@rftd ou @rafd75  vocês sabem o que pode ser esse erro no momento do método: RecepcionarLoteRps

Estou implementando um novo provedor: **WebISS**

> The message with Action '' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).

**Comment by RBACORP** [comment]
@rafd75  Sucesso!! Nota cancelada com Sucesso com o Código "0001" MARAVILHA.
Em relação aos Retornos, não consigo visualizar nenhuma Propriedade do Método MensagemRetorno.

Segue Print abaixo para melhor entendimento.
![acbr-vb6](https://cloud.githubusercontent.com/assets/24592756/21935363/5bd01b94-d994-11e6-94b0-57b35d49ec95.png)

**Comment by rafd75** [comment]
@RBACORP - então faltou apenas o lance do retorno, certo?

Fiz um teste aqui (usando Visual FoxPro). O Intellisense também não funciona... Mas eu consigo ler, sem nenhum problema ou implementar algo diferente, os valores das propriedades...

Fiz um teste aqui... Se eu tentar ler as propriedades antes de chamar algum evento (por exemplo, consultar um lote da nfse), eu também recebo um erro, como segue:

```
oNFSE = CreateObject("AcbrNfseProxy")
oNFSE.MensagemRetorno.XmlRetorno -> retorna o erro "Member MENSAGEMRETORNO does not evaluate to an object."

```

O que faz sentido, pois essa propriedade ainda contém NULL, já que a classe ainda não foi instanciada.

Mas se eu fizer o que está abaixo, funciona, ou seja, eu consigo o XML de retorno!

```
oNFSE = CreateObject("AcbrNfseProxy")
--- aqui entra todo o setup (prestador, certificado, etc)
oNFSE.ConsultarLote(0, 12345678, @MSGALERTA, @MSGERRO)
Messagebox(oNFSE.MensagemRetorno.XmlRetorno)

```

(Obs: O Intellisense do Visual FoxPro não funciona em nenhuma das situações)

O que você consumiu (qual função) antes de tentar ler o conteúdo do XmlRetorno ?

**Comment by RBACORP** [comment]
@rafd75 Cara Deve ser algum B.O com o meu VB6 então... pq ele não passa nem no teste de Compilação
se eu apertar CTRL + F5  ele já acusa o erro e não deixa nem executar o projeto... Achei que pudesse ser problema de registro da dll mas desregistrei e registrei novamente e o erro persiste.. :( 

Vou quebrar a cabeça mais um pouco aqui pra ver oque consigo...

eu consumo o método oNFSE.MensagemRetorno.XmlRetorno logo após o envio do lote:

ret = oNFSE.EnviarLote(numeroLote, False, False, msgAlerta, msgErro)
xmlLoteEnvio = oNFSE.MensagemRetorno.XmlEnvio
xmlLoteRetorno = oNFSE.MensagemRetorno.XmlRetorno
xmlLoteProtocolo = oNFSE.MensagemRetorno.Protocolo

**Comment by rftd** [comment]
Eu adicionei os atributos de COM Interop na classe de retorno a mesma deve funcionar agora.
Vou fechar esta Issue pois o assunto já não tem haver com o assunto principal dela, favor abrir uma nova issue para continuar.
