### ISSUE TITLE
Versão da dll

### ISSUE THREAD

**Issue by ThalisonSantos** [ACBrNet/ACBr.Net.NFSe#156]
Boa tarde pessoal não se alguem notou mas a dll esta com a versão anterior a que estava antes na nova versão do nuget

**Comment by ThalisonSantos** [comment]
na versão 1.5.1.1 do nuget a dll era essa mesma versão, na 1.5.1.2 do nuget a dll é 1.5.1.0

**Comment by rftd** [comment]
Sim eu sei qual o problema ??

**Comment by ThalisonSantos** [comment]
@rftd não que tipo de projeto vc tem , mas no winforms aqui ele gera um erro no form uma questão de referencia a versão da dll. ena versão da acbr.net.dfe.core tem o mesmo problema de versão e esta gerando um erro de metodo não encontrado
![erro](https://user-images.githubusercontent.com/22593917/118500804-7c66ea80-b6fe-11eb-895c-9c8b4735f64f.jpeg)

**Comment by rftd** [comment]
Cara o erro de versão esta na configuração do seu app ai, conferem em app.config que tu deve achar o local.
Sobre o outro erro ai é que tu ta usando uma versão antiga da NFSe com uma versão nova da DFe Core.

**Comment by ThalisonSantos** [comment]
resolvi valeu
