### ISSUE TITLE
[Dúvida] Chamada ao WS da prefeitura não funciona quando a aplicação está publicada no Azure ou local

### ISSUE THREAD

**Issue by armanelli** [ACBrNet/ACBr.Net.NFSe#161]
Olá!

Peço desculpas caso o issue esteja sendo aberto incorretamente, mas não sei onde tirar essa dúvida...

Fiz uma Web API em .Net Core, que inicialmente só faz uso do método ConsultaNFSePeriodo, rodando a API localmente funciona certinho. Faz a chamada ao ws da prefeitura e retorna as Notas. (Testei com os provedores BHISS e Ginfes)

Porém quando eu publico essa API tanto no Azure ou até em um Windows Server mesmo, por algum motivo não deixa completar a chamada ao WS das prefeituras.

Já testei algumas possibilidades:

1 - API está publicada na região Brazil South (imaginei que requisições de fora poderiam ser bloqueadas)
2 - Tentei trocar os protocolos utilizados
3 - Utilizei a ferramenta Remote Debug do Azure para debugar o código que está publicado, segue a exceção que recebo:

![image png 20071138af810e5e650dd135de00b8bd](https://user-images.githubusercontent.com/11942562/120921344-9e1e1680-c699-11eb-8743-259b91419a27.png)

Obs: Estou usando a propriedade CertificadoBytes para passar o certificado digital. 
Novamente, local parece ser OK para as prefeituras mas em outro ambiente não está sendo.

Alguém já passou por algo parecido?

Desde já, obrigado!

**Comment by rftd** [comment]
Pelo erro parece que algo aconteceu antes sequer de enviar.

**Comment by armanelli** [comment]
Ontem fiquei debugando o dia inteiro mas ainda não consegui achar o problema, local funciona e publicado no Azure não :(
Por hora como tive que entregar, estou recebendo os XML's do cliente e usando somente os métodos LoadXML de cada provedor, até eu conseguir verificar por que isso ocorre no ambiente do Azure.

Vou fechar aqui por que realmente não parece ser nada no código do ACBR, mas se eu encontrar a solução deixo aqui caso alguém veja isso no futuro. Obrigado.
