### ISSUE TITLE
Como Imprimir pelo componente?

### ISSUE THREAD

**Issue by ThalisonSantos** [ACBrNet/ACBr.Net.NFSe#163]
alguem tem algum exemplo de como imprimir a nfse pelo componente?

**Comment by rftd** [comment]
Tem no exemplo um componente de impressão feito com o FastReport Opensource, fora isso tu pode implementar o seu próprio.

**Comment by ThalisonSantos** [comment]
@rftd eu tentei mas sempre abre o report vazio, por isso queria saber se tinha alguem usando pra ver o que estou fazendo errado

**Comment by rftd** [comment]
Olha eu não sei se tem alguém usando mais nos meus testes funcionou corretamente.

**Comment by ThalisonSantos** [comment]
@rftd como passar um exemplo de como vc fez?

**Comment by rftd** [comment]
O exemplo é o que ta no repositorio ai, os meus testes so são feito neles.

**Comment by ThalisonSantos** [comment]
@rftd certo tudo bem, mas o que eu preciso passar pra impressão? pq eu consulto uma nfse ela retorna no objeto acbr, mas quando mando imprimir o report sai vazio

**Comment by Transis-Felipe** [comment]
@ThalisonSantos  Eu tb testei e dei certo.
Utilizei o projeto Demo e gerei um PDF com os dados.

**Comment by ThalisonSantos** [comment]
@transis2 eu não tentei com o demo do projeto mas coloquei um codigo semelhante e sai vazio o report

**Comment by rftd** [comment]
a folha sai toda em branco ou sem os dados ? 
Se a folha sai toda em branco é que não ta conseguindo carregar o arquivo do relatorio.

**Comment by ThalisonSantos** [comment]
@rftd  sai sem os dados mesmo com a nfse carregada no objeto acbr

**Comment by rftd** [comment]
Veja os dados são passados na linha 149.
`internalReport.RegisterData(Parent.NotasServico.ToArray(), "NotaServico");`
Use um debug e veja se os dados estão indo.

**Comment by ThalisonSantos** [comment]
@rftd ok vou testar e depois retorno aqui

**Comment by ThalisonSantos** [comment]
@rftd fiz o debug e os dados estão passando
![2021-07-15 (2)](https://user-images.githubusercontent.com/22593917/125841636-50639bf9-dc5b-401d-bc5d-166b5684fb44.png)
![2021-07-15](https://user-images.githubusercontent.com/22593917/125841698-ea953a95-5f8d-4156-96ca-a51bd61a452b.png)

**Comment by rftd** [comment]
Sinceramente não sei o que pode estar ocorrendo ai, eu simplesmente não consigo reproduzir o erro que tu fala.

**Comment by rftd** [comment]
Outra coisa que notei tu ta usando a versão full do fast e os testes que fizemos foi na versão OpenSource, pode ser este o motivo das diferenças, recomendo abrir no designer da versão full e ver se o campos estão corretos.

**Comment by rftd** [comment]
Resolvi o problema eu não tinha atualizado o report no repositorio.

**Comment by ThalisonSantos** [comment]
@rftd funcionou a impressão, mas tem algumas coisas erradas: aliquota iss é 2% saiu 200%
![2021-07-19](https://user-images.githubusercontent.com/22593917/126161156-762522df-6553-4fe8-9613-61820610df93.png)
![2021-07-19 (1)](https://user-images.githubusercontent.com/22593917/126161179-cad6c07b-83bd-4e09-9819-175f3a6a3c3c.png)
