### ISSUE TITLE
Invalid content was found starting with element 'Signature'. No child element is expected at this point

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#167]
Estou tendo o erro abaixo:

Estrutura do xml recebido incorreta. javax.xml.bind.MarshalException - with linked exception:[org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-complex-type.2.4.d: Invalid content was found starting with element 'Signature'. No child element is expected at this point.].
Correção : Valide as tags do xml antes de enviar.

Já viram erro semelhante ou tem alguma pista de como resolver ?

![image](https://user-images.githubusercontent.com/4941173/125954902-8610d6ee-4da2-4d3c-a82b-50be718d3a4c.png)

**Comment by rftd** [comment]
Pelo erro o provedor não espera que tenha assinatura ou no rps ou no lote.
Agora temos que ver se é em todo provedor ou apenas nesta cidade.

**Comment by Transis-Felipe** [comment]
> Agora temos que ver se é em todo provedor ou apenas nesta cidade.

É só nessa cidade, pois já uso este provedor com outras prefeituras.
Essas prefeituras só nascendo de novo mesmo...

Obrigado pela dica, vou atrás de um modelo de XML e verificar se tem alguma versão pra diferenciar dentro do provedor.

No programa de validação da prefeitura, o xml está certo.

![image](https://user-images.githubusercontent.com/4941173/126005856-ee5167b5-ed65-4fbf-bf42-0eb84212110e.png)

**Comment by rftd** [comment]
Neste caso pode ser erro no ws, entre em contato com a prefeitura.

**Comment by rftd** [comment]
Conseguiu avançar neste problema ?

**Comment by Transis-Felipe** [comment]
> Conseguiu avançar neste problema ?

Ainda não, estou tentando obter xml emitido pelo site da prefeitura para verificar se tem duas assinaturas.
Vou telefonar hj para a prefeitura, pq na sexta-feira eles não atenderam.

**Comment by Transis-Felipe** [comment]
Telefone eles não atendem. Devem estar vendo netflix enquanto fazem "home-office"
Mandei email e vou rezar para que alguém responda.

**Comment by Transis-Felipe** [comment]
Continuo aguardando o suporte. 
Já consegui falar com eles, mas ainda estão verificando.

**Comment by Transis-Felipe** [comment]
Parece que estava faltando username e password.

Uma coisa que pensei seria incluírmos uma guia no projeto demo para mostrar o soapenv:Envelope

![image](https://user-images.githubusercontent.com/4941173/126834620-44c9b59b-cc32-4dfc-801a-62f461f58d6a.png)

Para mostrar esses dados do soap, que ficam fora do xml

![image](https://user-images.githubusercontent.com/4941173/126834789-49bdc97b-d0f8-4712-ade2-9a8153500da2.png)

**Comment by rftd** [comment]
Nossa mais uma novidade os cara colocando coisas de bosta de novo.

**Comment by Transis-Felipe** [comment]
Posso fazer um PR com a validação desses campos, ao executar no provedor fiorilli ?

![image](https://user-images.githubusercontent.com/4941173/126837244-1dc691dc-df21-43c8-a21b-1d1b7a1a6e3e.png)

**Comment by rftd** [comment]
pode sem problema, mas lance um exception ali, acbrdfexcpetion ou communcationexception

**Comment by Transis-Felipe** [comment]
> pode sem problema, mas lance um exception ali, acbrdfexcpetion ou communcationexception

PR #169 
Tá, vou mudar para exception
