### ISSUE TITLE
NFSe Curitiba

### ISSUE THREAD

**Issue by Dheizon** [ACBrNet/ACBr.Net.NFSe#168]
Olá. Nesse projeto esta implementado o ISS de Curitiba?

**Comment by rftd** [comment]
Tem quer qual provedor é utilizado pela cidade e ver se o mesmo esta implementado.

**Comment by Dheizon** [comment]
Estava dando um olhada no componente e aparentemente não encontrei nenhuma implementação. Na documentação de integração disponibilizado pela prefeitura informa que o WebService segue o Modelo ABRASF.

**Comment by rftd** [comment]
Realmente eu vi aqui, ele é provedor proprio e segue o abrasaf v1, com algumas modificações.
Teria que criar um novo provedor e fazer os ajustes de acordo com este provedor.

**Comment by rftd** [comment]
Provedor criado pelo @Dheizon, obrigado pela contribuição.
