### ISSUE TITLE
Retorno dos métodos (Envio, ConsultaSituacao, ConsultaLote, talvez outros)

### ISSUE THREAD

**Issue by rafd75** [ACBrNet/ACBr.Net.NFSe#17]
@rftd - estou com um problema conceitual aqui. Vou tentar explicar.

1 - Enviamos um lote de RPS.... retornou TRUE

2 - Consultei a situação do lote... voltou "3", ou seja, processado com erros. e o método retornou TRUE. (OBS: No caso do GINFES, ao consultar a situação do lote, ele só retorna que foi processado com erro, mas não diz qual o erro. Para isso, eu preciso consultar o lote.)

3 - Consultei o lote, para pegar a mensagem do erro e fazer a correção. Após consumir o webservice, recebi a mensagem e entendi o erro (no caso aqui, usei o mesmo CNPJ do prestador para o tomador). Neste caso, ao consultar o lote, no GINFES, fiz assim:

XmlRetorno = cliente.ConsultarLoteRps(cabecalho, retornoWebservice.XmlEnvio);

e procuro, no "XmlRetorno" a tag "MensagemRetorno". Se eu encontrar essa TAG, significa que deu algum problema... faço um foreach e pego todas as mensagens: Erros.Add(evento).

Até aqui, tudo ok... o problema é que o ConsultarLoteRps retorna FALSE, pois existe um (ou mais) erros.

Pronto. Esse é o cenário A. (ocorreu um erro no xml enviado, e o provedor está nos alertando disso).

Mas pode ocorrer, por exemplo, de falhar ao tentar consumir o webservice. Neste caso, eu não chego a conseguir a mensagem de retorno, e ConsultarLoteRps também retornará FALSE. Esse é o cenário B (ocorreu um erro no aplicativo, no webservice, no provedor).

Independente da situação A ou B, a função vai retornar FALSE para a aplicação que está consumindo. Porém, a aplicação precisa tomar uma atitude diferente para cada caso. Explico:

Se houve um erro no XML enviado, a aplicação deve desconsiderar o lote/protocolo (uma vez que já foi processado) e mandar uma nova requisição (após o usuário corrigir o erro).

Se houve um problema de consumo do webservice, por exemplo, a aplicação não pode descartar o lote/protocolo, pois o mesmo pode ter sido processado com sucesso. Neste caso, a aplicação deve tentar consumir novamente o webservice.

No caso do FlexDocs, ele só retorna ERRO, quando não consegue consumir o webservice, ou falha o certificado, ou deu pau na aplicação, etc.... 

Quando foi consumido corretamente o webservice, independente da resposta obtida pelor provedor, ele sempre retorna TRUE, e repassa a mensagem (xml do provedor) para a aplicação, que por sua vez analisa a mensagem e toma a ação necessária. Ou seja, retornar TRUE ou FALSE no componente NFSe, leva em conta apenas se consumiu corretamente o webservice, e pronto. O resto (inteligência) fica por conta da aplicação que consumiu o componente.

Estou falando isso tudo, não pensando apenas no GINFES, mas se for o caso, todos os provedores (DSF, etc) devem seguir uma mesma lógica... assim, as aplicações que forem consumir o componente, vão seguir a mesma lógica, independente do provedor.....

Não sei se consegui explicar corretamente.

**Comment by rftd** [comment]
Para mim pode ser sem problemas só tem que mudar o comportamento no DSF e documentar esta regra de negocio para ser implementada nos próximos provedores.

**Comment by rafd75** [comment]
Vou implementar e mando um novo PR ...
