### ISSUE TITLE
'<', valor hexadecimal 0x3C, é um caractere de atributo inválido

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#176]
Oi, 

Desculpe pedir ajuda, mas talvez seja uma coisa simples pra ti e não estou conseguindo resolver.

Estou com a exception abaixo quando tenta montar o soapEnvelope:
'<', valor hexadecimal 0x3C, é um caractere de atributo inválido. Linha 1, posição 139.

![image](https://user-images.githubusercontent.com/4941173/127708989-35b11db2-a402-4c82-afa7-59c28f1a0696.png)

Cidade Itaitinga -CE (Provedor SpeedGov)
![image](https://user-images.githubusercontent.com/4941173/127709287-f35cc576-a0c3-4c97-aaf9-f3297977d24a.png)

**Comment by rftd** [comment]
Vou dar uma olhada aqui mais este tipo de erro geralmente é xml mal formado.

**Comment by Transis-Felipe** [comment]
Estranho que eu testei o XML do header e tb o XML dos dados. Só na hora de montar tudo com o soap que ele se perde.

**Comment by Transis-Felipe** [comment]
Achei o problema.
Tinha faltado uma aspa
Vou publicar a correção em breve.
