### ISSUE TITLE
Incluir Prefixo

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#180]
Boa tarde,

Tem alguma forma de incluir o prefixo nas tags sem ter que re-escrever todo GetXmlRps ?
Eu ví que no ginfes é usado um prefixo, mas precisou refazer todo xml.

Algo tipo o acbr faz nas configurações...

![image](https://user-images.githubusercontent.com/4941173/129626241-c458c844-43a2-41e5-8588-cc79681b474e.png)

**Comment by rftd** [comment]
Não me lembro de ter feito nada relativo a isso nas classes.
Mas tem um provedor que não me lembro que fiz uma função para adiconar prefixo em um xml já formado.
Provider ISSNet.

**Comment by Transis-Felipe** [comment]
Vou olhar, obrigado
