### ISSUE TITLE
Erro no provedor SystemPro

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#186]
Estou com o erro abaixo ao chamar o Channel.Request:

Tens alguma idéia sobre o que pode ser ? Autenticação dentro do soap eu ví que não é.

![image](https://user-images.githubusercontent.com/4941173/130289341-2bc53221-e7b2-4b85-b3aa-3f1580d40e34.png)

![image](https://user-images.githubusercontent.com/4941173/130289200-0513e824-e977-40a3-b079-5d7fe4ff97f6.png)

O soap está sendo gerado nesse padrão do ACBR:

![image](https://user-images.githubusercontent.com/4941173/130289713-358eb041-fbce-4b5c-bb71-ca29b085cace.png)

![image](https://user-images.githubusercontent.com/4941173/130289970-ce1b0207-d18d-4721-98ba-6001bc9724c1.png)

**Comment by rftd** [comment]
Pelo erro parece que faltou passar o certificado para a conexão.
