### ISSUE TITLE
Aplicação Demonstrativa

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#2]
Gostaria de saber se vai incluir no fonte uma aplicação demonstrativa, assim como fez no componente de Sat ??

**Comment by rftd** [comment]
Sim assim que estiver pronto para testes já ter uma aplicação para demonstração.

**Comment by leandrossantos** [comment]
@rftd já tem como disponibilizar uma aplicação de testes juntos com o fonte do componente, demonstrando como usá-lo?

**Comment by leandrossantos** [comment]
@rftd já tem mais alguma novidade da aplicação demonstrativa para disponibilizar?
