### ISSUE TITLE
Implementando provedor WebISS

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#24]
@rftd ou @rafd75 vocês sabem o que pode ser esse erro no momento do método: **RecepcionarLoteRps**

Estou implementando um novo provedor: **WebISS**

> The message with Action '' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver. Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).

**Comment by rafd75** [comment]
@leandrossantos , boa tarde!

Eu só fiz o GINFES até agora... (ainda não comecei com a NF Paulista) e quando eu fiz o GINFES, que fez a parte de assinaturas, foi o @rftd .

Infelizmente eu não consigo te ajudar agora. Talvez, quando eu fizer a parte de assinatura (contrato) da NF Paulista, eu passe a entender melhor disso ai... sorry!

**Comment by leandrossantos** [comment]
@rafd75 a assinatura do XML esta sendo feita perfeitamente, inclusive esta validando o XML pelo schema e está 100%.
O problema agora é na hora de enviar mesmo que deu esse erro acima.

**Comment by rafd75** [comment]
Desculpe... não estava falando da assinatura do xml... e sim na assinatura do método do webservice (não sei se é esse o termo correto).

Não sei se ajuda, mas neste link, várias pessoas comentam algumas soluções para esse erro:

http://stackoverflow.com/questions/5487791/contractfilter-mismatch-at-the-endpointdispatcher-exception

**Comment by leandrossantos** [comment]
@rftd me confirma uma coisa, analisando o resultado da consulta da url da **WebISS** vi que o retorno é bem parecido com o da **DSF**, se eu copiar as classes da **DSF** e alterar para **WebISS** e fazer as alterações necessárias você acha que vai funcionar?

Veja abaixo as urls dos provedores:
WebISS: [https://vilhenaro.webiss.com.br/servicos/wsnfse_homolog/nfseServices.svc?wsdl](https://vilhenaro.webiss.com.br/servicos/wsnfse_homolog/nfseServices.svc?wsdl)

DSF: [http://issdigital.pmcg.ms.gov.br/WsNFe2/LoteRps.jws?wsdl](http://issdigital.pmcg.ms.gov.br/WsNFe2/LoteRps.jws?wsdl)

**Comment by rftd** [comment]
provavelmente não pois tem que ver como é gerado cada schema se o provedor usa o mesmo namespace para todas as cidades e serviços entre outas coisas.
Pelo que eu vi o WebISS usa o padrão Abrasaf, eu to implementando o padrão AbrasafV2 se for o mesmo usado pelo WebISS pode usar ele como base para o provider

**Comment by rftd** [comment]
Me manda o codigo IBGE a cidade e o estado para eu adicionar nas cidades eu fiz uma classe aqui e quero testar.
Obs.: Lembrando que o provider ABRASFV2 ainda não tem leitura do xml.
         WebISS usa ABRASFV1 então não da para usar esta base mas o cliente já esta comunicando.

**Comment by leandrossantos** [comment]
@rftd a cidade é Vilhena / RO, o código IBGE dela é 1100304

**Comment by rftd** [comment]
Eu adicionei o provedor WebISS por favor faça testes.

**Comment by leandrossantos** [comment]
@rftd baixei e fiz um novo teste, agora o envio esta sendo feito corretamente e ja esta vindo o retorno do provedor, segue o retorno que deu:

> `<EnviarLoteRpsResposta xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.abrasf.org.br/nfse">`
`<ListaMensagemRetorno>`
`<MensagemRetorno>`
       `<Codigo>E1</Codigo>` 
       `<Mensagem>Assinatura do Hash não confere</Mensagem>`
       `<Correcao>Reenvie asssinatura do Hash conforme algoritmo estabelecido no Manual de Instrução da NFS-e</Correcao>` 
  `</MensagemRetorno>`
`<MensagemRetorno>`
  `<Codigo>E159</Codigo>` 
  `<Mensagem>1/1: CNPJ do prestador especificado no lote não confere com o prestador informado no RPS.</Mensagem>` 
  `<Correcao>Informe corretamente o CNPJ do prestador no lote e no RPS.</Correcao>` 
  `</MensagemRetorno>`
  `</ListaMensagemRetorno>`
  `</EnviarLoteRpsResposta>`

**Comment by rftd** [comment]
você utilizou o demo para fazer os testes correto, se foi o mesmo tem os dados do rps codificados direto no codigo é uso ainda apenas para teste ele não esta funcional, agora o hash da assinatura eu tenho que ver o que seria.

**Comment by leandrossantos** [comment]
@rftd dei uma analisada no XML gerado e adequei ao leiaute que a **ABRASF** e **WebISS** adotam e então o erro **E159** ficou resolvido mais o erro **E1** ainda continua.

**Comment by rftd** [comment]
Já sei o que pode ser quando sair aqui do hospital eu faço uns testes.

**Comment by leandrossantos** [comment]
@rftd com essa ultima versão ficou 100% transmitiu sem nenhum problema. Valeu.
