### ISSUE TITLE
Erro Certificado Digital A1 

### ISSUE THREAD

**Issue by RBACORP** [ACBrNet/ACBr.Net.NFSe#25]
Bom dia @rftd  após a ultima atualização... as propriedades do método MensagemRetorno ficaram visíveis para o VB6, porem a Assinatura com o Certificado Digital A1 parou de funcionar... me retorna o seguinte erro:  
Erro ao efetuar assinatura digital.
Referência de objeto não definida para uma instância de um objeto.

Percebi que a referencia: ACBr.Net.DFe.Core.dll foi alterada.
Voltando para a Versão anterior dos fontes o Certificado funciona mas o Método MensagemRetorno não rsrsrsrsrs
 
Abraço!

**Comment by leandrossantos** [comment]
@rftd seguindo o que o @RBACORP esta dizendo na continuidade dos testes aqui o problema da assinatura do lote de envio resolveu e as consultas estão dando o erro de assinatura que o colega informou ai acima.

**Comment by leandrossantos** [comment]
@RBACORP você esta usando a DLL no VB6?? tem como montar um pequeno exemplo pode ser apenas com 1 botão fazendo a parte de configuração, pq tentei aqui e não consegui no VB6.
