### ISSUE TITLE
Servidor Porto Alegre/RS

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#26]
@rftd tem como você confirmar pra mim se o servidor de Porto Alegre/RS é igual do WebISS que você esta implementando agora?

Segue o link com a documentação de Porto Alegre/RS

[http://portalnotalegal.portoalegre.rs.gov.br/default.php?p_secao=152](http://portalnotalegal.portoalegre.rs.gov.br/default.php?p_secao=152)

**Comment by rftd** [comment]
Pelo que eu vi é baseado no abrasf v1 mas pelo visto houve modificações no xsd sendo necessário ver que tipo de modificação foi feita para adequar e assim usar.
Você pode criar um provider usando de base a classe ProviderABRASF e gerar um cliente dos endereços deste provedor, e ir comparando as diferenças pelo xsd dos dois servidores.

**Comment by rftd** [comment]
Eu fiz um commit com a implementação inicial agora só precisa fazer as personalizações que o servidor tem em relação ao ABRASF v1 padrão.
