### ISSUE TITLE
Erro ao Validar XML

### ISSUE THREAD

**Issue by RBACORP** [ACBrNet/ACBr.Net.NFSe#27]
Bom dia @rftd, No momento de cancelar/Enviar a NFS-e o WebService está me retornando o erro:
[E160] Arquivo enviado fora da estrutura do arquivo XML de entrada. / Envie um arquivo dentro do schema do arquivo XML de entrada.

Dei uma olhada na estrutura do Xml que está sendo enviado usando o Método:
oNFSE.MensagemRetorno.XmlEnvio 
e notei que o encoding está assim:
<?xml version="1.0" encoding="utf-16"?>

UTF-8 foi alterado para UTF-16, procurei em todo o código mas não achei esse encoding...
Todos que achei estão com UTF-8 correto.
Esse erro só ocorre nessa ultima versão...
pode me ajudar?

Abraço!

**Comment by rftd** [comment]
Qual o provedor e serviço utilizado, UTF-16 é o padrão do Visual Studio.

**Comment by RBACORP** [comment]
@rftd  GINFES.  Enviar ou Cancelar

**Comment by rafd75** [comment]
@RBACORP ---- Se não me engano, esse problema só ocorre em ambiente de teste.

Faz um teste (para confirmar isso que eu disse)

Altera a propriedade Configuracoes.Geral.RetirarAcentos para TRUE e repete o teste... 

veja se passa.... Se passar (em homologação), é isso que eu te falei. No ambiente de PRODUÇÃO isso não é necessário... 

Da uma olhada na classe Proxy, que eu já tratei isso lá, no método SetupWebService:

```
// Ajusta as particularidades de cada provedor.
var provider = ProviderManager.GetProvider(oACBrNFSe.Configuracoes);
switch (provider.Name.ToUpper())
{
    case "GINFES":
        // Provedor Ginfes em ambiente de Homologação não aceita acentos. (Ambiente de Produção aceita normalmente.)
        if (oACBrNFSe.Configuracoes.WebServices.Ambiente == DFeTipoAmbiente.Homologacao)
            oACBrNFSe.Configuracoes.Geral.RetirarAcentos = true;
            break;
        default:
            break;
}
```

**Comment by RBACORP** [comment]
@rafd75 Fiz o teste que vc me pediu e continua o Mesmo erro....

**Comment by rftd** [comment]
corrigido no commit d60806f45c556ccd32b8027629a90f78b5e4863a

**Comment by RBACORP** [comment]
@rftd  o Enviar Corrigiu... mas o Cancelar ainda está com o mesmo problema...

**Comment by RBACORP** [comment]
@rftd Não sei se ajuda mas gravei o xml que está sendo enviado para o web service e está retornando com  erro.  
As infos de CNPJ E IM  foram alteradas somente para enviar aqui, no teste elas estão corretas 
Segue Anexo.
Renomeia o arquivo para .xml 
Abraço!

[teste.txt](https://github.com/ACBrNet/ACBr.Net.NFSe/files/712163/teste.txt)

**Comment by rftd** [comment]
já corrigi este erro mais tarde envio uma atualização.

**Comment by RBACORP** [comment]
@rftd  Obrigado fico no aguardo!

Abraço!
