### ISSUE TITLE
Usar DLL no VB6

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#28]
Gostaria de saber qual é o procedimento para conseguir usar a DLL no VB6.

Preciso dela funcionando no VB6 para concluir os testes com o provedor WebISS.

**Comment by RBACORP** [comment]
@leandrossantos Registra a dll usando o regasm e após efetuar o registro, referencia ela no vb6  em Project/References

Depois é só instacia-la dessa forma:
Dim ret as boolean
Dim oNFSE As ACBrNFSeProxy
 Set oNFSE = New ACBrNFSeProxy

ret = oNFSE.SetupWebService

ao digitar o "." (ponto) após o nome do objeto o vb vai te mostrar os métodos da dll

Abraço!

**Comment by leandrossantos** [comment]
Problema resolvido, valeu @RBACORP já consegui aqui 1 NFSe pelo provedor **WebISS** transmitida e autorizada.

:)

**Comment by DjanGomes** [comment]
poderiam me envia a dll.
