### ISSUE TITLE
Impressão de NFSe

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#29]
Gostaria de saber como estão fazendo sobre a impressão da NFSe.

Estão usando algum monitor de impressão?

**Comment by rftd** [comment]
A impressão ainda não foi implementada no NFSe, mas sera usando o gerador de relatório Fast Reports e esta sem previsão no momento, estou focando em estabilizar e adicionar novos provedores na biblioteca primeiro.

**Comment by leandrossantos** [comment]
Valeu @rftd pela força com o WebISS, próximo provedor para os testes será o de Porto Alegre/RS e depois já vou começar a ver também para a cidade de Ijui/RS.

**Comment by leandrossantos** [comment]
@rftd quando eu usava o provedor FissLex eu usava a DLL da FlexDocs e a parte da impressão eu passo o link direto da impressão.
No do WebISS eu não achei o link para montar para a impressão, se você conseguir por ai me avisa.

**Comment by rftd** [comment]
Porto Alegre ainda não esta completo precisa ajustar as diferenças entre o padrao ABRASF v1 e este servidor.
FissLex pelo site dele parecer ser o padrao ABRASF v1 sem modificações teria que testar para ver corretamente.
