### ISSUE TITLE
Provedores Betha, FissLex e Prouni

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#3]
Tem alguma previsão de implementa para os provedores Betha, FissLex e Prouni ??

**Comment by rafd75** [comment]
Leandro, bom dia!

Cheguei hoje (28/07/2016) aqui neste projeto. Na próxima semana, vou
analisar o código e verificar se posso ajudar no desenvolvimento.

Se tudo for conforme eu espero, vou implementar primeiro o provedor GINFES
(para a cidade de Ribeirão Preto e na sequencia para São Carlos).

Em seguida, devo fazer o provedor Betha (para Santa Cruz do Sul), mas não
será algo tão rápido.

Atualmente eu utilizo o FlexDocs (NFSe), mas eles mudaram a política de
desenvolvimento e não consigo mais licenciar para novas cidades... Preciso
colocar para funcionar em um cliente em São Carlos rapidamente (1 mês).
Espero que este projeto resolva o problema, pois tenho quebrado a cara com
projetos de terceiros (fechados).

Abs! ... (e se tudo der certo, conte com minha ajuda)

_Rodolfo Duarte__Computar_ | Desenvolvimento
(16) 3011-2768 / 3043-9460
rodolfo@computar.com.br

[image: Computar] http://www.computar.com.br

2016-07-28 11:25 GMT-03:00 leandrossantos notifications@github.com:

**Comment by leandrossantos** [comment]
@rafd75 eu também atualmente utilizo a DLL da FlexDocs, mais a empresa aqui esta expandindo para outras cidades e com essa nova política de vendas deles não tem como mais comprar licenças de NFSe para outras cidades, então estou atras de outras soluções.

**Comment by rafd75** [comment]
@leandrossantos - pois é...

Espero não ficar com pendências essa semana para começar a próxima semana com a mão nesse código.
