### ISSUE TITLE
Erro No Cancelamento NFS-e

### ISSUE THREAD

**Issue by RBACORP** [ACBrNet/ACBr.Net.NFSe#30]
@rftd  No Cancelamento está ocorrendo o seguinte erro:

[E303] O documento XML difere da assinatura. / O documento XML não pode conter alterações após a assinatura.

Certificado Digital A1 está sendo utilizado....

Abraço!

**Comment by rftd** [comment]
O resto dos serviços estão funcionando corretamnete ?

**Comment by RBACORP** [comment]
@rftd Sim... funcionam corretamente, somente o cancelar mesmo.

Abraço
