### ISSUE TITLE
Arquivo Municipios.nfse

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#32]
@rftd estou precisando criar o arquivo Municipios.nfse somente dos municipios que vou usar,estou tentado criar um do zero mais não consigo, dá erro de "End of stream encountered before parsing was completed" alguma ideia do que tenho que fazer para resolver esse problema e criar um novo arquivo do zero?

**Comment by rftd** [comment]
Para gerar um arquivo abra o demo vai em Gerenciador de Cidades la tem as cidades já cadastradas.
Remova e adicione conforme for necessario e salve um arquivo sera criado na pasta do demo com as cidades para utilizar, copie para pasta resources e recompile a dll e pronto esta pronto um arquivo de cidades personalizado.

**Comment by leandrossantos** [comment]
@rftd tem como deixar o arquivos municipios.nfse aberto em formato XML igual é o config, assim fica mais fácil a manutenção nele caso alguma prefeitura mude de provedor.

**Comment by rftd** [comment]
Todo código para manutenção do arquivo esta no ACBrNFSe de qualquer jeito é só abrir ele salvar e passar o path para ser carregado o novo arquivo.

**Comment by clsaad** [comment]
Olá,
Fiz esse procedimento utilizando a ultima versão atualizada pelo NuGet.
Abri o demo, atualizei o arquivo municipios.nfse e fiz a importação dele. Porém, ao importar ele retorna o seguinte erro:

        Dim oRPS As New ACBrNFSe

        oRPS.Configuracoes.Geral.ArquivoMunicipios = Server.MapPath(".\App_Data\eCNPJ\Municipios.nfse")

Erro:
Não é possível encontrar o assembly 'ACBr.Net.NFSe, Version=1.0.17325.1242, Culture=neutral, PublicKeyToken=d3bb9130f8b775a6'.
Descrição: Ocorreu uma exceção sem tratamento durante a execução da atual solicitação da Web. Examine o rastreamento de pilha para obter mais informações sobre o erro e onde foi originado no código. 

Detalhes da Exceção: System.Runtime.Serialization.SerializationException: Não é possível encontrar o assembly 'ACBr.Net.NFSe, Version=1.0.17325.1242, Culture=neutral, PublicKeyToken=d3bb9130f8b775a6'.


pode me ajudar? Obrigado

**Comment by rftd** [comment]
Então atualmente usamos serialização binario o que acaba linkando o arquivo a versão do assembly pretendo mudar para serialização em xml com compreeensão opcional em breve.

**Comment by clsaad** [comment]
Se eu baixar o codigo fonte disponivel e recompilar as 3 DLL's disponiveis,
pode funcionar?
Obrigado pelo pronto retorno Rafael.

Em 5 de abril de 2018 14:20, Rafael Teno Dias <notifications@github.com>
escreveu:

**Comment by gsysteminformaticarp** [comment]
Olá, estava utilizando a biblioteca normalmente com o provedor Ginfes, porem depois da ultima atualização das bibliotecas ACBr.Net.Core e ACBr.Net.DFe.Core para a versão 1.2.0, os métodos não funciona mais por exemplo quando tento enviar um rps retorna a seguinte exception:

System.MissingMethodException: 'Método não encontrado: 'System.String ACBr.Net.DFe.Core.CertificadoDigital.AssinarXml(System.String, System.String, System.String, System.Security.Cryptography.X509Certificates.X509Certificate2, Boolean)'.'

**Comment by rftd** [comment]
Assim que eu terminar a reestruturação do projeto para ficar compatível com .net Standard vou mudar o serializador para Xml assim ficando mais fácil a manutenção do mesmo.
