### ISSUE TITLE
Erro ao enviar RPS DSF/Campinas

### ISSUE THREAD

**Issue by ckyoto** [ACBrNet/ACBr.Net.NFSe#33]
Estou tentando usar o projeto p/ gerar nfse de Campinas em uma aplicação MVC5, 
e está ocorrendo o seguinte erro;

Message: O esquema de URI do provedor 'http' é inválido; esperado 'https'.
Nome do parâmetro: via

StackTrace:
 em System.ServiceModel.Channels.TransportChannelFactory`1.ValidateScheme(Uri via)
   em System.ServiceModel.Channels.HttpChannelFactory`1.ValidateCreateChannelParameters(EndpointAddress remoteAddress, Uri via)
   em System.ServiceModel.Channels.HttpsChannelFactory`1.ValidateCreateChannelParameters(EndpointAddress remoteAddress, Uri via)
   em System.ServiceModel.Channels.HttpsChannelFactory`1.OnCreateChannelCore(EndpointAddress address, Uri via)
   em System.ServiceModel.Channels.HttpChannelFactory`1.OnCreateChannel(EndpointAddress remoteAddress, Uri via)
   em System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
   em System.ServiceModel.Channels.ChannelFactoryBase`1.CreateChannel(EndpointAddress address, Uri via)
   em System.ServiceModel.Channels.ServiceChannelFactory.ServiceChannelFactoryOverRequest.CreateInnerChannelBinder(EndpointAddress to, Uri via)
   em System.ServiceModel.Channels.ServiceChannelFactory.CreateServiceChannel(EndpointAddress address, Uri via)
   em System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel(Type channelType, EndpointAddress address, Uri via)
   em System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   em System.ServiceModel.ChannelFactory`1.CreateChannel()
   em System.ServiceModel.ClientBase`1.CreateChannel()
   em System.ServiceModel.ClientBase`1.CreateChannelInternal()
   em System.ServiceModel.ClientBase`1.get_Channel()

por favor, alguém pode me auxiliar?

obrigado.

**Comment by rftd** [comment]
Favor testar e me reportar se o erro foi mesmo corrigido.

**Comment by ckyoto** [comment]
funcionou, td ok, obrigado!
