### ISSUE TITLE
Implementar ABRASF v2

### ISSUE THREAD

**Issue by rftd** [ACBrNet/ACBr.Net.NFSe#34]
Implementar a geração e leitura dos XML do RPS e NFSe no padrão ABRASF v2

**Comment by leandrossantos** [comment]
@rftd alguma novidade na classe ABRASF v2 ???
Estou precisando implementar o provedor Betha nesse padrão e estou tendo problemas na hora de assinar o XML gerado.

**Comment by rftd** [comment]
Eu tava meio ocupado ultimamente, amanha eu vou dar uma olhada nisso e vejo se consigo terminar ela logo.

**Comment by leandrossantos** [comment]
@rftd valeu, veja ai se consegue fechar o provedor Betha que já faço os testes e te aviso.
