### ISSUE TITLE
Novo Provedor

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#36]
Olá @rftd sobre o provedor WebISS pode colocar como concluído já estou com ele em produção em clientes.

O provedor de Porto Alegre estou em fase de testes e agora também estou precisando do provedor Betha, vi que já tem as classes dele, só não vi como usá-las.

Tem como ver pra mim por favor?

**Comment by rftd** [comment]
Betha ainda não está implementado só tem uma uma idéia de como fazer

**Comment by leandrossantos** [comment]
@rftd se puder ver sobre o provedor Betha, já tenho clientes que vão usar esse provedor para fazermos os testes.

**Comment by rafd75** [comment]
OPa.... ... tenho 3 clientes que utilizam BETHA, mas todos eles estão na solução fornecida pela FlexDocs.... Quando sair esse provedor, também pretendo trocar lá.... vou acompanhar de perto.

**Comment by leandrossantos** [comment]
@rftd estou vendo que o provedor **Betha** tem 2 versões, 1.0 e 2.02, a versão 1.0 tem uma URL para cada método e a versão 2.02 é uma URL única igual já tem funcionando no **WebISS** e **Porto Alegre**

Confirma ai pra mim se esse código do **Betha** que está no componente se é a versão 1.0 ou 2.02.

Veja no link abaixo o material do **Betha**.
[https://e-gov.betha.com.br/e-nota-test/ambienteteste.faces](https://e-gov.betha.com.br/e-nota-test/ambienteteste.faces)

**Comment by leandrossantos** [comment]
@rftd  tem como verificar ai como esta o componente para o provedor Betha, se falta algo e se tem como implementar o que falta?

**Comment by rftd** [comment]
O provedor Betha ainda esta no zero ultimamente estou sem tempo para nada. 
Assim que arranjar tempo eu tento finalizar as coisas
