### ISSUE TITLE
Impressão

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#37]
@rftd já tem alguma coisa ai pronta da impressão?

Já tenho o arquivo frx da impressão só não estou conseguindo usar ele no componente.

**Comment by leandrossantos** [comment]
@rftd segue me anexo o arquivo frx da impressão da NFSe, pode dar uma olhada nele para colocarmos no componente.

Verifica ai pra mim se está tudo e como usá-lo no componente.



[DANFSe.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/883715/DANFSe.zip)

**Comment by leandrossantos** [comment]
@rftd tem como pelo menos você montar a classe de impressão e pegar esse frx que anexei e criar a classe nele certinho, os campos eu acerto eles e te mando de volta paras você colocar no componente. Estou amarrado nisso e não consegui ainda colocar essa impressão pelo componente.

**Comment by rftd** [comment]
Impressão implementada favor testar.
