### ISSUE TITLE
Porto Alegre

### ISSUE THREAD

**Issue by rafd75** [ACBrNet/ACBr.Net.NFSe#42]
Boa tarde... 

Na apresentação do projeto ACBR.Net.NFSe, consta que o provedor Porto Alegre está "Em Implementação".

Quem fez essa implementação? e o que está faltando?

Estou com um possível cliente (consulta), e já vou me preparar para colocar isso em produção...

**Comment by leandrossantos** [comment]
Oi @rafd75 foi eu quem solicitei isso para o @rftd e ele implementou, nos testes que fiz está tudo OK.
Meu cliente que solicitou acabou desistindo do projeto :(

**Comment by rafd75** [comment]
Hum... bom saber... 

Você chegou a testar todos os eventos? Envio, Retorno, etc... ?

Bacana... De qq forma, se der certo lá, vou repetir os testes ... mas a conversa com o possível cliente está apenas começando... vamos ver se vira alguma coisa... 

Abs!

**Comment by leandrossantos** [comment]
@rafd75 fiz os testes básicos e tudo funcionou certinho. Pode ser que tenha passado alguma coisa despercebida por mim.
Agora minha necessidade é o provedor Betha, estou com 3 clientes precisando 2 de SC e um de TO

**Comment by rafd75** [comment]
O Betha, eu tenho 2 clientes que já utilizam... mas é da época que adquiria a licença da FlexDocs... 

Assim que possível, minha ideia é deixar tudo com o ACBR, e aposentar de vez o FLexDocs (para NFSe)

Valeu!

**Comment by leandrossantos** [comment]
Aqui na empresa também usávamos FlexDocs, mais dai tivemos uma mudança de provedor na cidade que usavamos a DLL e tive que ir atras de uma solução e achei aqui que na época foi para o provedor WebISS que está em pleno vapor usando em nossa aplicação feita em VB6. Agora estamos com a demanda de 3 possíveis clientes em SC e TO e já verifiquei que lá o provedor é o Betha então estou precisando dele o quanto antes. Já que para essas cidades não temos nenhuma licença comprada na FlexDocs para conseguir comprar novas licenças, então tem que ser uma nova DLL mesmo.

**Comment by rafd75** [comment]
é... FlexDocs (NFSe) ferrou geral...

O mesmo ocorreu (alguns anos atrás) com o CobreBemX - para boletos, estou usando esse: https://github.com/BoletoNet/boleto2net (que foi uma atualização que fiz a partir do projeto original - BoletoNet)

Prometi que só em último caso vou investir em ferramenta fechada... Daqui para frente, só código aberto. Não ligo de pagar, duro é ficar na mão deles... Não da.
