### ISSUE TITLE
Provedor São Paulo

### ISSUE THREAD

**Issue by devmarcossouza** [ACBrNet/ACBr.Net.NFSe#43]
Ao usar a função de carregar o XML não está carregando a  nota fiscal.

**Comment by rafd75** [comment]
@devmarcossouza - Vc está tentando usar um XML de NF mesmo certo...?

Eu que implementei SP... Se não me engano, eu deixei isso para depois que eu conseguisse autorizar a NFSe, e acabou ficando... (Na verdade, em nosso sistema, eu uso as funções da classe Proxy para incluir uma nova nota fiscal, ao invés de carregar o XML).

Se vc me mandar o XML, eu faço por aqui, mas não sei quando vou conseguir fazer isso. Estou enrolado com uma atualização do módulo financeiro que deve levar umas semanas ainda. Terminando isso, minha ideia é tentar (junto com o @rftd ) acertar um problema que estou tendo da DLL com o certificado digital A3. Poderia encaixar isso (leitura do XML) nesse bolo, mas se for urgente, melhor você implementar essa função ai.

**Comment by devmarcossouza** [comment]
No momento estou dando um append no lotebuilder para ver se funciona, assim que tiver tempo posso mexer no método do loadXml e depois mandar um request pra vcs.

**Comment by rafd75** [comment]
fechou.
