### ISSUE TITLE
Provedor Betha v2

### ISSUE THREAD

**Issue by rondosoftlss** [ACBrNet/ACBr.Net.NFSe#45]
boa noite @rftd 

primeiramente, parabéns pelo projeto, esta excelente.

vi que nessa ultima atualização que você fez você colocou no description que adicionou o Provedor Betha v2, baixei os fontes mais não consegui localizar, poderia verificar ai, estou disposto a efetuar todos os testes desse provedor pra você, basta disponibilizar ai que faço os teste.

valeu

**Comment by rftd** [comment]
@rondosoftlss fiz algumas correções no provedor Betha2 você poderia testar o mesmo agora ?

**Comment by felipeborba-dev** [comment]
@rftd Sabe mais ou menos como está a integração do Betha v2 ? Estou precisando implementar para um cliente e posso contribuir
