### ISSUE TITLE
Provedor Betha - problemas ao assinar XML Rps

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#47]
Oi @rftd atualizei o projeto aqui e vi que você implementou as rotinas ABRASFv2 que incorpora o provedor Betha, ao efetuar os testes verifiquei que esta dando erro ao assinar o XML, na rotina Enviar na primeira chamada da assinatura retornoWebservice.XmlEnvio = CertificadoDigital.AssinarXmlTodos(xmlEnvio, "Rps", "InfDeclaracaoPrestacaoServico", "Rps", Certificado);

Acredito que que seja algum problema por causa da estrutura do XML na versão 2.02, visto que tem 2 tag Rps dentro do XML, acredito que possa ser isso que esta atrapalhando a assinatura.

**Comment by leandrossantos** [comment]
@rftd já conseguiu ver sobre esse problema da assinatura do XML do provedor Betha?

Tentei aqui de várias formas e não consegui.

**Comment by rftd** [comment]
Olha @leandrossantos eu estou sem tempo no momento, mas se quiser me contratar para mexer exclusivamente nesta parte me envie um email em rfteno@gmail.com.

**Comment by rafd75** [comment]
@leandrossantos - só completando a resposta do @rftd === se precisar de referência, eu posso te passar... Em um dos provedores que implementei, fiz esse "contrato" com ele para me ajudar... 

Sim, é um projeto free, mas na ocasião eu estava sem tempo, e chegamos num valor que resolveu o meu problema e ficou bom para o Rafael... As vezes vale a pena!

**Comment by leandrossantos** [comment]
@rftd e @rafd75 obrigado pelo contato, o @rftd dispensa referencias, já conheço o trabalho dele através dessas DLL que disponibiliza aqui para nós. Já enviei o email para você @rftd vamos continuar a conversa por lá e vermos se conseguimos resolver mais essa.

Valeu pessoal.

**Comment by rafd75** [comment]
Beleza!!!

**Comment by rftd** [comment]
eu enviei umas atualizações talvez arrume seu problema.
