### ISSUE TITLE
Esses provedores que temos disponíveis qual deles exigem certificado digital?

### ISSUE THREAD

**Issue by robertorp** [ACBrNet/ACBr.Net.NFSe#48]
Esses provedores que temos disponíveis qual deles exigem certificado digital?

To perguntando pois quero implementar algum em uma aplicação minha. Mas não pode ter exigência de certificado digital, pois não tenho o mesmo disponível.

**Comment by rftd** [comment]
Basicamente todos aqui implementados pedem certificado digital.

**Comment by robertorp** [comment]
Esse certificado é um pfx igual o da nf-e ou difere?

**Comment by rftd** [comment]
Sim é o mesmo certificado da NFe

**Comment by robertorp** [comment]
ok, obrigado
