### ISSUE TITLE
Sugestão de alteração na classe Provider

### ISSUE THREAD

**Issue by rafd75** [ACBrNet/ACBr.Net.NFSe#5]
1 - Criar um overload para o método LoadXml onde seja possível passar a codificação do arquivo xml,

2 - Criar um overload para o método LoadXml onde serja possível passar uma string contendo o próprio xml (em memória) ao invés do nome do arquivo, considerando também, a codificação da string.

**Comment by rftd** [comment]
O primeiro overload pode ser criado, no segundo é so colocar um tratamento na classe que vai estar recebendo os dados para checar se o arquivo existe se existir trata como arquivo senão como string.

**Comment by rafd75** [comment]
Se estiver tudo OK com o merge  do github.com/ACBrNet/ACBr.Net.NFSe/pull/8 , pode fechar esse issue.
