### ISSUE TITLE
[Dúvida] Novos Provedores 

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#51]
> @rftd primeiramente meus parabéns, baixei a versão que você subiu no dia 24/12 e o provedor Betha v2 está funcionando perfeitamente, estou com um outro cliente para testar a WebISS v2 assim que ele fizer os testes e me dar um feedback eu te aviso.

Só me tira uma dúvida, os provedores **FISSLEX** e **Vitória** seguem o mesmo conceito da Abaco e WebISSv1 que já tem implementado na DLL, confirma ai pra mim, tenho 2 colegas que desenvolvem e que estão precisando para esses provedores.

**Comment by rftd** [comment]
Eu preciso da documentação e das urls dos provedores para esta vendo como funciona eles.

**Comment by leandrossantos** [comment]
Segue os dados solicitados:
- FissLex
     Documentação: https://sinop.fisslex.com.br/fiss-lex/mainportal/index.html
     URLs: 		
> Homologação
> 			RecepcaoLoteRPS: https://demo.fisslex.com.br/fiss-lex/servlet/aws_recepcionarloterps
> 			ConsultaLoteRPS: https://demo.fisslex.com.br/fiss-lex/servlet/aws_consultaloterps
> 			ConsultaNFSeRPS: https://demo.fisslex.com.br/fiss-lex/servlet/aws_consultanfseporrps
> 			ConsultaSitLoteRPS: https://demo.fisslex.com.br/fiss-lex/servlet/aws_consultarsituacaoloterps
> 			ConsultaNFSe: https://demo.fisslex.com.br/fiss-lex/servlet/aws_consultanfse
> 			CancelaNFSe: https://demo.fisslex.com.br/fiss-lex/servlet/aws_cancelarnfse
>
> Produção
> 			RecepcaoLoteRPS: https://sinop.fisslex.com.br/fiss-lex/servlet/aws_recepcionarloterps
> 			ConsultaLoteRPS: https://sinop.fisslex.com.br/fiss-lex/servlet/aws_consultaloterps
> 			ConsultaNFSeRPS: https://sinop.fisslex.com.br/fiss-lex/servlet/aws_consultanfseporrps
> 			ConsultaSitLoteRPS: https://sinop.fisslex.com.br/fiss-lex/servlet/aws_consultarsituacaoloterps
> 			ConsultaNFSe: https://sinop.fisslex.com.br/fiss-lex/servlet/aws_consultanfse
> 			CancelaNFSe: https://sinop.fisslex.com.br/fiss-lex/servlet/aws_cancelarnfse

- Vitória/ES:
   Documentação: http://nfse.vitoria.es.gov.br/doc/documentacao.cfm
   URL: 
>       Homologação: https://wsnfse.vitoria.es.gov.br/homologacao/NotaFiscalService.asmx?WSDL
>       Produção: https://wsnfse.vitoria.es.gov.br/producao/NotaFiscalService.asmx?WSDL

**Comment by rftd** [comment]
FissLex é Abrasf V1 e Vitoria é Abrasf V2.
Vou ver se adiciono depois.

**Comment by leandrossantos** [comment]
@rftd valeu meu amigo, muito obrigado.

**Comment by leandrossantos** [comment]
@rftd você acha que se eu pegar os arquivos da WebISS v1 copiar e renomear eles para a FissLex vou conseguir usar?

Veja ai que ai já vou adiantando aqui.

**Comment by rftd** [comment]
Não pois o FissLex usa o xml do nfse e rps padrão abrasf, mas o webservice é padrão proprio deles ou seja bagunça.

**Comment by leandrossantos** [comment]
@rftd boa tarde, Feliz Ano Novo atrasado, rsrs.

Conseguiu incluir a Fisslex e Vitória ai para eu conseguir testar aqui?

**Comment by rftd** [comment]
não to sem tempo no momento.
