### ISSUE TITLE
Plano futuro

### ISSUE THREAD

**Issue by jaedson-barbosa** [ACBrNet/ACBr.Net.NFSe#52]
Poderíamos fazer uma espécie de mapa para sabermos tudo que ainda falta ser implementado, afinal pelo que parece, o componente ainda não pode ser usado por todas as cidades do Brasil.
Basicamente podia ser feita uma lista com todas as grandes cidades brasileiras e se já há suporte para ela. Caso não haja, pode ser adicionado algum link que nos ajude a implementar tudo que é preciso e contribuir com o projeto.

Falo isso porque meu sistema já faz NFe, estou implementando NFCe e muita gente pede NFSe, seria interessante se fizéssemos algo parecido com o que existe no FocusNFe. Em que só existe uma entrada simplificada.
Pode dar trabalho, mas estou disposto a ajudar, só preciso que me deem uma direção a seguir.

**Comment by rftd** [comment]
@JaedsonBarbosa Diferente dos outros DFes a NFSe não tem padrão nacional ele é implementada por cada município da forma que eles quiserem ou seja podemos ter 5.570 variações de NFSe.
Em NFSe não falamo de cidades e sim de provedores, pois a cidade pode mudar de provedor como muda de prefeito o projeto já tem uma simplificação dos campos que uma NFSe pode ter e temos já uns 8 Provedores implementados que podem atender vários municípios só o ginfes que eu saiba atende 67 municípios isso que eu sei não é um numero oficial e pode variar de acordo com o tempo.
Então o correto é fazer a implementação do outros provedores que tem na pasta de schemas o problema é que cada 1 faz a coisa de sua própria maneira gerando retrabalho direto.

**Comment by leandrossantos** [comment]
@JaedsonBarbosa o problema é esse que o @rftd disse, o padrão, pois cada provedor tem o seu e as prefeituras podem trocar de provedor de uma hora para outra, eu mesmo estou com essa situação, tenho um cliente que a cidade usava Betha e agora mudou para WebISS. Ai já viu né.
Sem falar que tem o padrão ABRASFv1 e ABRASFv2.
Não vejo a hora de sair um leiaute/padrão de WS nacional único, parece que existe um projeto piloto para isso só não sei se está em pratica já.

**Comment by jaedson-barbosa** [comment]
Como eu sei o padrão que cada cidade usa? Onde posso obter mais informações desse projeto piloto?
Então vocês querem implementar todos aqueles schemas? São muitos! É necessário adotar um padrão.
Pra mim, o principal é saber quais cidades cada provedor atende ou qual provedor cada cidade usa.
Existe um jeito fácil de obter essa informação?

**Comment by JaedsonBarbosa** [comment]
Então vocês querem implementar todos aqueles schemas? São muitos! É necessário adotar um padrão.

**Comment by JaedsonBarbosa** [comment]
Pra mim, o principal é saber quais cidades cada provedor atende ou qual provedor cada cidade usa.
Existe um jeito fácil de obter essa informação?

**Comment by rftd** [comment]
Como já disse não tem padrão e sim tem que implementar aquelas pasta toda.
Agora no componente já é diferente você tem as classes no padrão Abrasaf mas dependendo do provedor tu vai ter que preencher de forma especifica que aquele provedor espera.
O jeito de descobrir o provedor é acessando o site da prefeitura em questão ou entrando em contato com eles, lembrando que nem todas prefeituras tem NFSe.

**Comment by jaedson-barbosa** [comment]
Então vocês não tem nenhum componente pra descobrir o provedor? Que pena 🙁
Naquela pasta schemas há os schemas de todos os provedores do Brasil?

**Comment by rftd** [comment]
La tem todos os provedores que eu retirei do ACBr para pascal, mas acredito que tenha mais visto que foi implementados novos provedores no mesmo recentemente.

**Comment by jaedson-barbosa** [comment]
@rftd Tinha como você atualizar a pasta e colocar esses novos provedores?
