### ISSUE TITLE
WEBISS v2.02

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.NFSe#53]
@rftd  poderia me confirmar se o componente já esta compatível com o provedor WEBISS v2.02, hoje uso o componente no provedor WEBISS na versão 1 ainda, mais recebi um email da prefeitura da cidade de Vilhena/RO dizendo que vão migrar para a versão 2.02.

**Comment by leandrossantos** [comment]
Acabei de dar uma conferida no código e vi que você adicionou o WEBISS v2.02, estarei efetuando novos testes e qualquer coisa entro em contato. Obrigado

**Comment by EvandroSaccani** [comment]
@rftd bom dia, pode por o WebISSv2 como concluido também, testei aqui e está tudo funcional.
