### ISSUE TITLE
Erro Após Atualização das Bibliotecas 

### ISSUE THREAD

**Issue by PauloGama95** [ACBrNet/ACBr.Net.NFSe#54]
Olá, estava utilizando a biblioteca normalmente com o provedor Ginfes, porem depois da ultima atualização das bibliotecas ACBr.Net.Core e ACBr.Net.DFe.Core para a versão 1.2.0, os métodos não funciona mais por exemplo quando tento enviar um rps retorna a seguinte exception:

System.MissingMethodException: 'Método não encontrado: 'System.String ACBr.Net.DFe.Core.CertificadoDigital.AssinarXml(System.String, System.String, System.String, System.Security.Cryptography.X509Certificates.X509Certificate2, Boolean)'.'

**Comment by rafd75** [comment]
@rftd - esse problema não é o mesmo que ocorreu aqui, onde eu acabei retornando as DLLs na versão antiga... e posteriormente você havia resolvido e me passado as DLLs para teste?

obs: não me recordo se consegui fazer o teste... fizemos?

**Comment by rftd** [comment]
Eu estou fazendo a atualização e a reestruturação do projeto para poder ficar compativel com o .net standard e assim que terminar vai funcionar normalmente com as novas versões das outras libs.

**Comment by rftd** [comment]
Corrigido já.
