### ISSUE TITLE
Projeto

### ISSUE THREAD

**Issue by marcosmarchiore** [ACBrNet/ACBr.Net.NFSe#55]
Olá, gostaria de saber o status do projeto.

**Comment by rftd** [comment]
Temos alguns servidores funcionais já sendo usado em produção.
Outros ainda em carência de testes pela comunidade.

**Comment by rafd75** [comment]
@marcosmarchiore boa tarde

Aqui eu uso em produção os provedores Ginfes (Ribeirão Preto e São Carlos) e também NF Paulistana (São Paulo)

Mais umas duas semanas, vou passar a usar também NF Carioca...

**Comment by marcosmarchiore** [comment]
Tenho clientes em duas cidades que usam desta empresa 
https://www.notacontrol.com.br
E estou em estudo para implementação em minha aplicação e gostaria da opnião de vocês se possível.

**Comment by rftd** [comment]
Poste a documentação da mesma para analise.

**Comment by rftd** [comment]
Parece ser ABRASAF v1 se os webservices estiverem no padrão correto é rápido até implementar.
Analisando aqui parece ser super rápido e fácil implementar.

**Comment by marcosmarchiore** [comment]
Olá, segue manual de integração.

https://s3-sa-east-1.amazonaws.com/medias.ciranda.me/entities/1/fecc5acd678f7dfbb27834b5a048287bf9beba51.pdf

Portal 
http://www.issnetonline.com.br/cascavel/online/Login/Login.aspx

Pelo que vi logo na capa, @rftd  tem ABRASAF, acredito que e o padrão usado.
