### ISSUE TITLE
Esse projeto atende o município de Recife ?

### ISSUE THREAD

**Issue by MisaelBeray** [ACBrNet/ACBr.Net.NFSe#58]
Boa tarde, Me desculpe o incomodo, mas preciso construir um emissor de NFS-e pro município de recife e gastaria de saber se o projeto esta funcionando corretamente para lá. Já utilizei outros projetos de vocês e gostei muito, e gostaria de saber se posso desenvolver algo baseado nesse projeto de NFSe. 

Alguém poderia me ajudar ?

**Comment by rafd75** [comment]
@MisaelBeray , boa tarde.

Aqui utilizamos o ACBR.NET.NFSE para Ribeirão Preto e São Carlos (Provedor GINFES), Nota Paulistana (SP) e também a Nota Carioca (RJ)... 

Vou te dar uma dica.... um dos provedores (não lembro se GINFES ou SP), eu que implementei (me tomou um tempo isso).... .... e  quando apareceu a necessidade do provedor do RJ, eu estava atolado de tarefas aqui e não consegui fazer... Acabei "terceirizando" essa implementação com o @rftd ---- RECOMENDO MUITO!!!...  Ganhei muito tempo e ele me entregou o provedor direitinho e esteve disponível na fase de testes no cliente.  No final, deixamos o provedor para quem quiser utilizar no fonte do GITHUB...

Fala com ele........  Quanto mais gente usando a biblioteca, mais provedores, melhor vai ficar!!!

Abs!

**Comment by rftd** [comment]
Boa tarde o nosso componente não tem o provedor do recife ainda, mas pelo que eu li ele usa a versão 1 do modelo da ABRASF, nos temos uma classe base para ser utilizada em provedores deste modelo, se o provedor seguir corretamente o modelo deve ser facil implementar o mesmo.

@rafd75 você fez o provedor de SP e me auxiliou na implementação do GINFES.

**Comment by MisaelBeray** [comment]
Muito obrigado pelo retorno @rftd  e @rafd75, Vou analisar o projeto de vocês e ver se é complicado fazer uma adaptação para que possa utilizar o mesmo.

Se tiverem alguma noticia nova que possa ajudar, estarei acompanhando.

Abs!

**Comment by rafd75** [comment]
@MisaelBeray --- não sei sua urgência... mas joga na mão do Rafael que ele desenrola para vc... 

boa sorte ai! ... abs!
