### ISSUE TITLE
Emissão ginfes em Maceió/Alagoas

### ISSUE THREAD

**Issue by ThalisonSantos** [ACBrNet/ACBr.Net.NFSe#59]
tentei utilizar o emissor mas estou recebendo esse erro
`<ns4:Mensagem>Não é permitido o uso de Descontos Condicionados no município.</ns4:Mensagem>
<ns4:Correcao>Caso esteja utilizando RPS, remova a tag de Descontos Condicionados. Se a emissão da NFS-e estiver sendo executada OnLine, deixe o valor do campo em 0,00.</ns4:Correcao>`
mesmo sem passar nenhum valor na criação do rps a tag é criada automaticamente com valor 0 quando é executado o método acbrNFSe.NotasFiscais.AddNew() como proceder?

**Comment by rafd75** [comment]
@ThalisonSantos , talvez, na linha abaixo, incluir um if (EmissorDiferenteDeRecife) , deve resolver...

https://github.com/ACBrNet/ACBr.Net.NFSe/blob/94c6f49b907180eb616709d0c25d5d2162149c01/src/ACBr.Net.NFSe.Shared/Providers/Ginfes/ProviderGinfes.cs#L559

**Comment by rftd** [comment]
Estranho se esta zerado não deveria ser gerado a TAG como esta especificado em ocorrência, vou verificar.

**Comment by rafd75** [comment]
Verdade -> Ocorrencia.MaiorQueZero

**Comment by rafd75** [comment]
Verdade -> Ocorrencia.MaiorQueZero

**Comment by rafd75** [comment]
Verdade -> Ocorrencia.MaiorQueZero

**Comment by rftd** [comment]
Teria como postar um exemplo de como esta preenchendo pois não vi nada no código que possa estar ocasionando este erro.

**Comment by ThalisonSantos** [comment]
> Teria como postar um exemplo de como esta preenchendo pois não vi nada no código que possa estar ocasionando este erro.

@rftd  eu usei o exemplo do codigo só inseri a cidade de Maceió na lista de cidades.
var nfSe = acbrNFSe.NotasFiscais.AddNew();
quando o método acima é executado ele já cria na classe Serviços.Valores o desconto condicionado como 0 mesmo na parte de valores estando comentado a campo vai para o RPS

**Comment by rftd** [comment]
Ok, depois me passa os dados da cidade de Maceió para eu adicionar oficialmente ao repositório.

**Comment by ThalisonSantos** [comment]
@rftd Maceió Alagoas IBGE 2704302 Siafi 2785 Provedor Ginfes

**Comment by tuelito** [comment]
Bom dia! Para cidade de Capivari/SP (GINFES) está com o mesmo que o problema ThalisonSantos para Maceió/Goiás. Será que teria que fazer a mesma alteração no emissor @rftd ?
