### ISSUE TITLE
Classe Nota Fiscal - Renomear algumas propriedades (normalizar)

### ISSUE THREAD

**Issue by rafd75** [ACBrNet/ACBr.Net.NFSe#6]
**1 - Renomear DhRecebimento -> DataEmissao**
(para seguir o mesmo padrão da RpsSubstituido.DataEmissaoNfseSubstituida)

**2 - Renomear Prestador.CPFCNPJ -> Prestador.CpfCnpj**
(para seguir o padrão do Tomador.CpfCnpj e IntermediarioServico.CpfCnpj)

**3 - Renomear UF para Uf (ou) Uf para UF**
(Prestador, Tomador estão UF / OrgaoGerador Uf)

**Comment by rafd75** [comment]
**4 - IdentificacaoRPS.Numero -> IdentificacaoRPS.NumeroRPS**
(para manter o padrão do RPSSubstituido.NumeroRPS)

**5 - RPSSubstituido não contém a propriedade Tipo**
(para manter o padrão do IdentificacaoRPS - não sei se neste caso se aplica, pois podemos mandar um "RPS" do tipo "cupom" ou "Nota Fiscal Conjugada". Talvez seja impossível "substituir" um RPS do tipo "cupom". Se for o caso, desconsiderar.)

**Comment by rafd75** [comment]
Classe RetornoWebService

Provedor DSF entende a "DataEnvioLote" enquanto Ginfes entende "DataRecebimento" --- talvez renomear para "DataLote" fique com um nome mais genérico, que se encaixe melhor para qualquer uma dos provedores.

Não sei se alguns provedores controlam a Data de Envio e também a Data de Recebimento. Neste caso, a melhor solução é ter 2 propriedades.

Por enquanto, estou usando DataEnvioLote para guardar o retorno do Ginfes (Data de Recebimento do Lote).

**Comment by rftd** [comment]
Nas Data seria melhor colocar as duas
pois a propriedade tem que deixar claro o tipo de data que é.

**Comment by rftd** [comment]
A outros propriedades pretendo fazer uma limpa e uma padronização no FDS para ficar mais fácil de entender as mesmas.
