### ISSUE TITLE
Problemas de Emissão Coplan - Sinop//MT

### ISSUE THREAD

**Issue by EvandroSaccani** [ACBrNet/ACBr.Net.NFSe#60]
Estou com problemas na emissão usando o provedor Coplan com a cidade Sinop/MT

Segue em anexo o arquivo xml gerado que esta sendo enviado e a mensagem de retorno é: 
**Referência de objeto não definida para uma instância de um objeto.**

[lote-152.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/3378302/lote-152.zip)

**Comment by rafd75** [comment]
@EvandroSaccani , boa tarde!

Infelizmente eu não uso esse provedor... não vou conseguir te ajudar...
Mas você não consegue depurar o código e verificar onde está dando esse erro?

Você já implementou outros provedores (ou cidades) usando a Biblioteca? ... (só para saber se o erro está localizado nessa cidade/provedor)

**Comment by EvandroSaccani** [comment]
@rafd75 boa tarde!

Sim, eu uso no provedor WebISSv2 e funciona perfeitamente, a questão agora é que um de nossos clientes abriu uma filial em Sinop/MT e lá o provedor da NFSe é o Coplan. Vi que aqui na lib tem (em testes) então atualizei aqui para fazer os testes e acabei me deparando com essa mensagem na hora do envio.
E sim, estou debugando aqui, é bem na hora de executar o método abaixo
`retornoWebservice.XmlRetorno = cliente.RecepcionarLoteRps(GerarCabecalho(), retornoWebservice.XmlEnvio);`

E então cai direto para Exception retornando a mensagem: **Referência de objeto não definida para uma instância de um objeto.**

**Comment by rafd75** [comment]
bom... 

O máximo que vou conseguir te passar por aqui, é verificar se "cliente" está instanciado... (imagino que sim)... e se o GerarCabecalho() não está gerando o erro.

O mais provável é ter algo dentro do "RecepcionarLoteRps" mesmo ... você não consegue "entrar" no método e identificar que objeto está nulo?

**Comment by EvandroSaccani** [comment]
@rafd75 

Debugando passo a passo veja onde é que ocorre o problema.

[http://prntscr.com/odbq7s](http://prntscr.com/odbq7s)

**Comment by rftd** [comment]
Você esta salvando os arquivos de comunicação com o servidor ?
Configuracoes.WebServices.Salvar

**Comment by EvandroSaccani** [comment]
@rftd  sim, vou anexar aqui os arquivos criados pela DLL.

[Rps-20190711-1.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/3382033/Rps-20190711-1.zip)

[lote-154-env.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/3382039/lote-154-env.zip)

**Comment by rftd** [comment]
não tem o arquivo *_ret.xml, pois o erro acima é como se não houvesse respostas do servidor por isso não foi feito a desserialização do xml e por isso a classe vem nula.

**Comment by EvandroSaccani** [comment]
Não @rftd veja no print abaixo, eele faz esse caminho das setas.

Não cai onde está o X.

[http://prntscr.com/odmzy7](http://prntscr.com/odmzy7)

**Comment by rftd** [comment]
era para gerar o arquivo ret do mesmo jeito, dentro da classe do webservice ele também gerar o arquivo de envio e de retorno, bastando setar a propriedade que disse acima como true.

**Comment by EvandroSaccani** [comment]
@rftd 

`retornoWebservice.XmlRetorno = cliente.RecepcionarLoteRps(GerarCabecalho(), retornoWebservice.XmlEnvio);`

Desse código acima vai direto pro catch

**Comment by EvandroSaccani** [comment]
@rftd 

O `cliente.RecepcionarLoteRps(GerarCabecalho(), retornoWebservice.XmlEnvio)` está retornando vazio e indo direto para o  catch, assim não passa pelo GravaEmDisco que gera o -ret

**Comment by EvandroSaccani** [comment]
@rftd 

Estou anexando o arquivo de log, talvez lhe ajude em algo.

[ACBrNFSe.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/3382384/ACBrNFSe.zip)

**Comment by rftd** [comment]
Analisando

**Comment by EvandroSaccani** [comment]
@rftd não querendo ser chato, mais conseguiu ver alguma coisa?

Procurei na internet e não achei nada sobre isso.

**Comment by rftd** [comment]
não consegui uma resposta correta do servidor ainda, ele sempre retorna um erro, que não consegue ler o xml enviado para ele.

**Comment by EvandroSaccani** [comment]
@rftd bom dia. alguma novidade? conseguiu pegar a resposta correta do servidor?

também estou tentando aqui, mais também não estou conseguindo.

**Comment by EvandroSaccani** [comment]
@rftd conseguiu alguma coisa?? Eu tentei aqui mais não obtive sucesso.

Agora estou mexendo na MDFe aqui no sistema, mais também estou precisando dessa NFSe da Coplan.

**Comment by rftd** [comment]
Ainda com o mesmo problema mesmo gerando o lote idêntico ao ACBrNFSe do pascal ele ainda reclama de erro 417, eu enviei as modificações para o repositório para que você possa testar ai também.

**Comment by EvandroSaccani** [comment]
@rftd blz, vou testar sim.

Vou anexar aqui um .zip que peguei de um aplicativo escrito em C# que esta funcionando, o aplicativo é o UNINFE funciona igual o AcbrMonitor.

Veja se ele pode te ajudar.

[Coplan.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/3420149/Coplan.zip)

**Comment by rftd** [comment]
Achei o problema, logo envio a correção.

**Comment by EvandroSaccani** [comment]
@rftd opa, que noticia boa.

Os codigos que te mandei ajudaram?

**Comment by rftd** [comment]
Sim os códigos que mandou deram a dica necessária para o mistério, já enviei os arquivos favor testar.

**Comment by EvandroSaccani** [comment]
@rftd beleza, vou baixar e testar aqui, qualquer coisa eu te aviso.

Muito obrigado.

**Comment by rftd** [comment]
@EvandroSaccani funcinou ?

**Comment by EvandroSaccani** [comment]
@rftd funcionou perfeitamente, muito obrigado.

Só precisei fazer um pequeno ajuste na classe **ProviderABRASF2** no método **EnviarSincrono** na segunda assinatura:

> retornoWebservice.XmlEnvio = XmlSigning.AssinarXml(retornoWebservice.XmlEnvio, "EnviarLoteRpsEnvio", "LoteRps", Certificado);

O nome do nó EnviarLoteRpsSincrono está faltando, ou melhor trocado está EnviarLoteRpsEnvio, troquei para o de baixo e deu certinho até o método sincrono.

> retornoWebservice.XmlEnvio = XmlSigning.AssinarXml(retornoWebservice.XmlEnvio, "EnviarLoteRpsSincronoEnvio", "LoteRps", Certificado);

**Comment by rftd** [comment]
Correção enviada.
E não se esqueça se possível contribua com o projeto https://www.padrim.com.br/acbrnet.

**Comment by EvandroSaccani** [comment]
> Correção enviada.
> E não se esqueça se possível contribua com o projeto https://www.padrim.com.br/acbrnet.

Pode deixar. Muito obrigado pela ajuda.
