### ISSUE TITLE
Provedor ISSONLINE_ASSESSORPUBLICO

### ISSUE THREAD

**Issue by EvandroSaccani** [ACBrNet/ACBr.Net.NFSe#61]
@rftd gostaria de mais uma vez lhe agradecer pelo que tem feito nesse componente para nos ajudar.
Me ajudou com o servidor COPLAN e hoje estamos usando ele já em produção 100%
Também verifiquei que o provedor WebISSv2 também está todo funcional, pode até tirar o (teste) dele.

Só que agora apareceu uma consulta pra o provedor ISSONLINE_ASSESSORPUBLICO para as cidades Lins/SP e Araçatuba/SP

**Comment by rftd** [comment]
Infelizmente estou sem tempo para desenvolver, ainda mais este provedor que segue padrão próprio de xml e de envio.

**Comment by rftd** [comment]
Se puder depois poste o material sobre este provedor, schema, documentos e url de homologação

**Comment by rftd** [comment]
Fechando issue por falta de retorno do usuário.
