### ISSUE TITLE
Exemplo

### ISSUE THREAD

**Issue by adrianotrentim** [ACBrNet/ACBr.Net.NFSe#62]
Pessoa, estou meio perdido em como utilizar a biblioteca, alguém teria um exemplo completo pra eu dar uma olhada?

**Comment by rafd75** [comment]
@adrianotrentim , boa tarde...

da uma olhada nessa classe (veja os métodos e como cada um seta as propriedades)... 

https://github.com/ACBrNet/ACBr.Net.NFSe/blob/master/src/ACBr.Net.NFSe.Proxy/ACBrNFSeProxy.cs

deve te ajudar com suas dúvidas iniciais.... Estou na correria aqui, mas vou tentando te ajudar...

**Comment by adrianotrentim** [comment]
Opa, consegui fazer cominucar, agora tenho recebido um erro E165 - O campo AliquotaServicos é númerico e deverá ter tamanho máximo de 5,2, ou seja, 5 números inteiros e dois decimais. para o Ginfez... olhando o código fonte, ProviderGinfes, Ele está formatando realmente com 4 casas decimais.... Alguém utilizando Ginfes normalmente? está errado mesmo essa implementação?

**Comment by rftd** [comment]
o @rafd75 usa o ginfes a meses e ele mesmo que implementou este provider e não relatou nenhum problema do tipo.

**Comment by rafd75** [comment]
@adrianotrentim ... 

Tenta passar o "índice" ao invés do "percentual"

Ex: Se for 3%, e você estiver informando 3.0000 , altere para 0.0300 - entendeu? 

E me fala se funcionou...

**Comment by adrianotrentim** [comment]
Erro meu aqui, como estou usando json, na hora de converter pra decimal estava computando milhar... resolvido. Uma dúvida @rafd75 , existe alguma forma de recuperar o retorno serializado, padronizado? ou seja, existe alguma classe no projeto, que pegue todos os retornos e mostre os erros como propriedades?

**Comment by rafd75** [comment]
@adrianotrentim bom dia...

Essa questão de tratar o retorno em propriedades,, não tem não...

**Comment by adrianotrentim** [comment]
Não sei se me expressei mal, mas por exemplo, quando dá um erro na emissão, no ginfez que estou usando, volta um XML com a mensagem de erro. a única forma de ler esse xml é manual? Não tem alguma classe desenvolvida que lê isso e retorna um objeto, contendo uma lista de código e msg de erro?

**Comment by rafd75** [comment]
Então... eu acho que não tem não... 

Aqui, eu pego o XML mesmo... acabei tratando na aplicação...

@rftd - existe isso? não né?

**Comment by adrianotrentim** [comment]
blz, vou estudar de fazer algo parecido pra facilitar nossa vida.

**Comment by rafd75** [comment]
ai sim.... valeu!

**Comment by rftd** [comment]
Mano tu chegou a ver os fontes isto tem já implementado desda da 1ª versão da biblioteca.

**Comment by rafd75** [comment]
kkk . Passou batido aqui... Como eu já tratava o XML anteriormente (FlexDocs), não precisei alterar nada no meu aplicativo.

**Comment by adrianotrentim** [comment]
Estou olhando a 2 dias apenas, não vi tudo não.... pode me dizer onde olhar?

**Comment by rftd** [comment]
Todo serviço retorna uma instância da classe RetornoWebservice de uma olhada nas propriedades da mesma.

**Comment by adrianotrentim** [comment]
Mas essa classe não volta msg de erro, volta um xml completo?

**Comment by adrianotrentim** [comment]
disfarça, tem uma lista de Erros

**Comment by adrianotrentim** [comment]
Agora, ao tentar cancelar, me dá um erro de referencia inválida ao aplicar a assinatura, alguém passou por isso?

**Comment by rafd75** [comment]
Não tenho tido problema com isso.
Mas aqui, utilizo a classe Proxy do projeto:

CancelarNFSe(string codigoCancelamento, string numeroNFSe, string motivoCancelamento, ref string mensagemAlerta, ref string mensagemErro)

tenta informar codigoCancelmento = '0001' e veja se passa.

**Comment by adrianotrentim** [comment]
nada, diz "Erro ao efetuar assinatura digital.", inner = "Referencia invalida ou não é unica."... o duro que é que não consigo debugar o código pois aqui não compila, por causa da versão do MSBuild

**Comment by adrianotrentim** [comment]
tbm estou utilizando a classe proxy

**Comment by rftd** [comment]
você programa em C# e esta utilizando a classe proxy por qual motivo ?

**Comment by adrianotrentim** [comment]
achei mais fácil... os métodos estão prontos, então só instanciei ela e boa....

**Comment by adrianotrentim** [comment]
var oACBrNFSe = new ACBrNFSeProxy();

                var serieCertificado = oACBrNFSe.SelecionarCertificado(ref msgAlerta, ref msgErro);

                if (string.IsNullOrEmpty(serieCertificado))
                    throw new Exception("Você deve selecionar um certificado digital!");

                ret = oACBrNFSe.SetupArquivos(
                    Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Schemas", "NFSe"),
                    true,
                    caminhoSalvar,
                    ref msgAlerta,
                    ref msgErro);

                ret = oACBrNFSe.SetupWebService(
                    Convert.ToInt32(nfse.Empresa.EnderecoPrincipal.IdCidade),
                    (int)DFeTipoAmbiente.Homologacao,
                    serieCertificado,
                    "",
                    ref msgAlerta,
                    ref msgErro);

                var protocolo = "";

                ret = oACBrNFSe.CancelarNFSe("0001", nfse.Numero.ToString(), nfse.MotivoCancelamento.ToString(), ref msgAlerta, ref msgErro);

**Comment by adrianotrentim** [comment]
agora outro BO, na homologação pra Ribeirão Preto, o código de tributação 00010500 passou, na produção não vai nem por Jesus, fala que o código de tributação é inexistente.... Cancelamento na homologação ainda com o erro na hora de assinar... estou tentando emitir em produção pra ver se o erro persiste...

**Comment by rafd75** [comment]
Cód Lista Serviço = '01.05'
Cód Tributação = '01.05.00 / 00010500'

deve passar... quanto ao cancelamento, não sei te falar o que pode ser...

**Comment by adrianotrentim** [comment]
Código de Tributação OK. agora vou tentar fazer debugando pra ver esse erro de assinatura no cancelamento. o procedimento que postei acima está correto?

**Comment by adrianotrentim** [comment]
Caros, baixei o VS2019, baixei os fontes, versão compilada funcionou o cancelamento, não deu mais o erro de assinatura.
