### ISSUE TITLE
Prefeitura de Sertãozinho / SP

### ISSUE THREAD

**Issue by adrianotrentim** [ACBrNet/ACBr.Net.NFSe#63]
Estou tentando emitir para prefeitura de Sertãozinho, é a SMAR APD, e eles utilizam XML modelo ABRASF... porém quando mando emitir aparece um erro:
"Município não cadastrado"
na função configurações de WebServices.

Sabem me dizer se está implementado? Acredito que o padrão esteja, porém não os WebServices, como posso implementar?

**Comment by rftd** [comment]
Provedor SMAR APD não esta implementado, você tentar implementar, mas já aviso nenhum provedor segue o padrão ABRASF correto sempre precisa de adaptação para funcionar correto.

**Comment by rftd** [comment]
@adrianotrentim foi adicionado o provedor SmarAPDABRASAF que é da cidade de sertãozinho, favor fazer teste me mandar um feedback.
E não se esqueça se possível contribua com o projeto https://www.padrim.com.br/acbrnet.

**Comment by adrianotrentim** [comment]
@rftd , eu estou liberando um PR hj...... fiz o provedor da Smar... kkkkkk.... me passa seu e-mail, vou te mandar o que fiz, dá uma olhada, as vezes se juntar os 2 fica melhor.... o que fiz está 100% funcional.

**Comment by adrianotrentim** [comment]
@rftd , fiz os testes com o teu, não está funcionando, vou terminar esse que estou fazer e fazer o PR. aqui só falta o cancelamento que estou terminando hj.

**Comment by rftd** [comment]
Estranho eu testei aqui no SoapUI e funcinou so as resposta que foram tipo, seu CNPJ não ta liberado para isso e tals.

**Comment by adrianotrentim** [comment]
Tá com erro de schema.... aqui pra mim nem validou

**Comment by rftd** [comment]
em qual método ?

**Comment by rftd** [comment]
Lembrando que o SmarAPD tem 2 Schema, um padrão ABRASAF 2.04 e um próprio dele

**Comment by adrianotrentim** [comment]
Validação.... por exemplo, no método de envio de lote, a versão 2.04, o CNPJ do emitente tem que estar dentro de uma tag "<Prestador>"... o seu já está sem.... mas calma, o meu tá funfando legal e tá bem escrito, vou fazer a PR vc dá uma olhada.... fiz alguns ifs dentro do código tbm, pois a prefeitura de sertãozinho não permite algumas tags, etc.....

**Comment by adrianotrentim** [comment]
sim, to usando o ABRASF 2.04

**Comment by adrianotrentim** [comment]
Além do que, eu criei o padrão do abrasf 2.04 que mudou umas tags, e criei o Smar herdando dele.... vai funcionar para mais gente...

**Comment by rftd** [comment]
Blz, manda o PR que já analiso

**Comment by adrianotrentim** [comment]
@rftd , PR 69.... funcionando 100% com ABRASF 2.04 e SmarAPD. Testado e em Produção!
