### ISSUE TITLE
Provedor Belo Horizonte

### ISSUE THREAD

**Issue by sonik-br** [ACBrNet/ACBr.Net.NFSe#66]
A alguns anos implementei o provedor para belo horizonte. Está funcionando.
Fiz baseando na implementação do provedor Porto Alegre.
Agora decidi enviar o código aqui, e parei para fazer uma limpeza no código.
Percebi que dentro da classe do Provider que criei, a propriedade Name ficou como "Porto Alegre". Teria algum problema deixar assim?
Ao mudar para "Belo Horizonte", tive problema com os arquivos de schema. Criei a pasta. Passou a dar erro de System.ServiceModel.CommunicationObjectFaultedException.
Se puder deixar como porto alegre, vou subir o código. Se não puder, peço ajuda para solucionar esse problema.

**Comment by rftd** [comment]
Da erro no schema pois o nome do provedor é usado para localizar a pasta, ou seja se mudar para Belo Horizonte basta criar uma pasta com este nome e copiar os schemas para la.

**Comment by sonik-br** [comment]
Criei a pasta com o conteúdo correto (mesmo de Porto Alegre).
Após criar a pasta passou a dar erro System.ServiceModel.CommunicationObjectFaultedException

**Comment by rftd** [comment]
Seguinte faz um pull request que ai eu posso ver o código e auxiliar melhor

**Comment by sonik-br** [comment]
Criei o PR. Está configurado como Porto Alegre. Da forma que está, funciona.
Para testar, estou utilizando o botão "Consultar Situação do Lote" no app de demo.
Ao mudar a string para Belo Horizonte (e criar a pasta com o schema), passa a dar erro no arquivo BeloHorizonteServiceClient.cs conforme abaixo:

![belohorizonte](https://user-images.githubusercontent.com/16923826/72160660-71c77300-339d-11ea-9738-be3971e6bcd0.png)

**Comment by rftd** [comment]
Eu fiz umas alterações checa se agora funciona.

**Comment by sonik-br** [comment]
Aqui deu exatamente o mesmo erro

**Comment by rftd** [comment]
Eu fiz mais uns ajustes e deu certo a consulta situação aqui.
![image](https://user-images.githubusercontent.com/299476/72195324-1bcbed00-33e8-11ea-9e3b-b853d8cecf04.png)

**Comment by sonik-br** [comment]
O envio agora não está funcionando.
Reparei que você deixou o método gerarStringLoteRps dentro do Abrasf apenas, visto que Porto Alegre e Belo Horizonte herdam ele.
Porem, repare que o xml de Porto Alegre e Belo Horizonte são diferentes.

As diferenças que lembro de cabeça são:

PORTO ALEGRE
xmlLote.Append($"<GerarNfseEnvio {GetNamespace()}>");
xmlLote.Append($"<LoteRps Id=\"L{lote}\">");


BELO HORIZONTE
//tag diferente
xmlLote.Append($"<EnviarLoteRpsEnvio {GetNamespace()}>"); 
//adiciona o atributo versão
xmlLote.Append($"<LoteRps Id=\"lote\" versao=\"1.00\" {GetNamespace()}>");


O que seria o correto nesse caso? Implementar condições no arquivo do Abrasf?

**Comment by rftd** [comment]
Gerar e EnviarLote são métodos distinto e tem haver com o método Sincrono e Assincrono, o gerar é no Sincrono e existe sim no servidor de Belo Horizonte.

![image](https://user-images.githubusercontent.com/299476/72265088-41c4dd80-35f2-11ea-93db-80abee850ef8.png)

Como esta na imagem, qual o erro que ta rolando e qual o método que tu esta tentando.

**Comment by sonik-br** [comment]
Cliquei no botão "Gerar e Enviar Lote RPS", deu erro de falta de atribulo "versão".
Esse atributo, não existe no Abrasf / Porto Alegre, mas existe me Belo Horizonte.

**Comment by rftd** [comment]
O padrão não é de Porto Alegre é o ABRSASF Versão 1, vou ver aqui o que pode estar ocorrendo.

**Comment by rftd** [comment]
No caso você esta falando da declaração xml, que provedor maluco, querer declaração xml no body do request, sem falar que não atrapalha em nada não ter, estes provedores cada vez mais malucos.

**Comment by rftd** [comment]
Nestas casos pode colocar na classe do webservice tipo assim

![image](https://user-images.githubusercontent.com/299476/72268953-27423280-35f9-11ea-893d-96441e5076c5.png)

**Comment by sonik-br** [comment]
Colocar no provider nao resolveu.
Esse metodo RecepcionarLoteRPS nem é chamado pois dentro da implementação do Abrasf tem validação, e dá erro antes de chamar o método.

![image](https://user-images.githubusercontent.com/16923826/72278225-5022f180-3612-11ea-8a2c-56251be01324.png)

**Comment by rftd** [comment]
e qual o erro pois a declaração não daria erro na validação do schema.

**Comment by sonik-br** [comment]
Na validação do esquema, dá erro de não possuir o atributo "Versao".
Olha no print acima, na parte de Watch, deixei o erro selecionado.

**Comment by rftd** [comment]
Fica zen finalmente entendi tava olhando na TAG errada, vou disponibilizar um update.
Obs.: Já tinhamos os schemas de BH o nome do provedor no ACBr era BHISS, vou manter o nome do ACBr para ficar mais fácil.

**Comment by rftd** [comment]
Update enviado

**Comment by sonik-br** [comment]
Testei e aparentemente está tudo certo! 👍 
Vou fazer mais testes e colocar em produção. Pode fechar se quiser.

**Comment by rftd** [comment]
Ok qualquer novo erro é so  abrir uma nova issue.
