### ISSUE TITLE
Classe Nota Fiscal (Regime Tributação e Simples Nacional)

### ISSUE THREAD

**Issue by rafd75** [ACBrNet/ACBr.Net.NFSe#7]
No caso do Ginfes, temos duas propriedades: Uma para o RegimeEspecialTributacao, e outra para OptanteSimplesNacional.

No projeto, temos apenas RegimeEspecialTributacao, onde o valor 9 indica SimplesNacional.
Pelo que entendi (no Ginfes), teoricamente os optantes pelo simples nacional ficariam assim:
tag RegimeEspecialTributacao com o valor 6 (MicroEmpresarioEmpresaPP)
tag OptanteSimplesNacional com o valor 1 (Sim)

Então, para gerar o XML, se o objeto NotaFiscal.Regime = 9 (simples), eu gero as tags com 6 e 1.
E para ler, se a tag optanteSimples for 1, eu gero NotaFiscal.Regime com 9.

Teoricamente funcionará sempre... mas pensando aqui (olhando o código abaixo), se um dia, (ou talvez já exista e eu não peguei essa situação ainda) houver a necessidade de gerar um XML com 5 (MEI) e 1(simples nacional), não daria certo.

Pergunta: Não seria melhor ter 2 propriedades?
(Pelo que percebi, no caso do DSF, esse tipo de identificação é diferente em regime / tipoTributação)

```
          // Simples Nacional
            if (root.ElementAnyNs("OptanteSimplesNacional")?.GetValue<char>() == '1')
            {
                ret.RegimeEspecialTributacao = RegimeEspecialTributacao.SimplesNacional;
            }
            else
            {
                // Regime Especial de Tributaçao
                switch (root.ElementAnyNs("RegimeEspecialTributacao")?.GetValue<char>())
                {
                    case '1':
                        ret.RegimeEspecialTributacao = RegimeEspecialTributacao.MicroEmpresaMunicipal;
                        break;
                    case '2':
                        ret.RegimeEspecialTributacao = RegimeEspecialTributacao.Estimativa;
                        break;
                    case '3':
                        ret.RegimeEspecialTributacao = RegimeEspecialTributacao.SociedadeProfissionais;
                        break;
                    case '4':
                        ret.RegimeEspecialTributacao = RegimeEspecialTributacao.Cooperativa;
                        break;
                    case '5':
                        ret.RegimeEspecialTributacao = RegimeEspecialTributacao.MicroEmpresarioIndividual;
                        break;
                    case '6':
                        ret.RegimeEspecialTributacao = RegimeEspecialTributacao.MicroEmpresarioEmpresaPP;
                        break;
                }
            }






```

**Comment by rftd** [comment]
MEI nunca vai ser simples nacional, são regimes diferentes.

**Comment by rafd75** [comment]
--- ok, neste caso, o código acima irá funcionar perfeitamente com o Ginfes.

Se o regime especial for simples, informamos as tags Regime=6 e Simples=1.

**Comment by rftd** [comment]
https://blog.contaazul.com/mei-x-simplesnacional/
