### ISSUE TITLE
Provedor Coplan

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#73]
Boa tarde,

Primeiramente parabéns pelo projeto.
Estou testando o provedor Coplan e verifiquei que o campo DataEmissao no envio do rps está usando ProviderABRASF2, que por sua vez monta a data com TipoCampo= DatHor

O provedor Coplan exige a data com TipoCampo= Dat
Ví que a tag é montada corretamente com esse tipo no ProviderABRASF204
            rps.AddChild(AdicionarTag(TipoCampo.Dat, "", "DataEmissao", 10, 10, Ocorrencia.Obrigatoria, nota.IdentificacaoRps.DataEmissao));

Abaixo o erro apontado pelo validador do schema:
O elemento 'http://www.abrasf.org.br/nfse.xsd:DataEmissao' é inválido - O valor '2020-01-29T16:07:44' é inválido dependendo do tipo de dados 'http://www.w3.org/2001/XMLSchema:date' - A cadeia de caracteres '2020-01-29T16:07:44' não é um valor Date válido.

Alguém saberia como trocar o tipoCampo para montar corretamente a DataEmissao ?

Grato,

**Comment by rftd** [comment]
não o Schema dele diz ser DateTime, este erro esta vindo do webservice deles ?
![image](https://user-images.githubusercontent.com/299476/73421369-0158a580-42fc-11ea-99fd-e192f9464450.png)

**Comment by Transis-Felipe** [comment]
Oi @rftd,

Obrigado pelo retorno.

Estou mandando as telas do visual studio mostrando a validação.

Eu usei o projeto ACBr.Net.NFSe.Demo para esse teste.

![VS](https://user-images.githubusercontent.com/4941173/73454792-8d46ed80-434d-11ea-8fd5-802d19d99c2d.jpg)

Aqui eu mostro que realmente pegou o provider = Coplan

![1](https://user-images.githubusercontent.com/4941173/73447379-5e288000-433d-11ea-985b-4756b546a1ce.png)

Aqui eu conferi que ele está utilizando o schema da pasta Coplan

![SCHEMA2](https://user-images.githubusercontent.com/4941173/73447388-62549d80-433d-11ea-9437-2a1c85ef69f6.png)

Eu baixei o projeto terça-feira e conferi o schema onde realmente diz esperar datetime.

Abri no notepad o arquivo schema que o projeto utiliza:

![SCHEMA](https://user-images.githubusercontent.com/4941173/73447387-62549d80-433d-11ea-9092-1052b5126ec6.png)

Aqui aparece a mensagem de erro no validador do schema

![ErroSchema](https://user-images.githubusercontent.com/4941173/73447386-62549d80-433d-11ea-8658-9f5373efb10a.png)




Obrigado desde já pela ajuda.

**Comment by rftd** [comment]
Eu adicionei o provedor Abrasf 2.01 que deve resolver seu problema, favor atualizar e testar novamente.

**Comment by Transis-Felipe** [comment]
Boa tarde!

Obrigado pelo retorno.

Agora passou pelo validador do schema sem erros! Ótimo!

Mas está trancando no envio do RPS :-(

![Exception](https://user-images.githubusercontent.com/4941173/73472394-bbd2c180-4369-11ea-8304-8d8c1b9ec9f9.png)

Abaixo os dados que usei para teste:

![Demo](https://user-images.githubusercontent.com/4941173/73472416-c8571a00-4369-11ea-8217-2790d772ca3e.png)

Message:
SOAP-ENV:Client - Error reading trib:Recepcionarloterpsrequest
Message: Error reading trib:nfse_web_service.RECEPCIONARLOTERPS

Stacktrace:

   at ACBr.Net.NFSe.Providers.CoplanServiceClient.TratarRetorno(XDocument xmlDocument, String[] responseTag) in C:\Users\Felipe\Desktop\ACBr.Net.NFSe-master\src\ACBr.Net.NFSe\Providers\Coplan\CoplanServiceClient.cs:line 232
   at ACBr.Net.NFSe.Providers.NFSeSOAP11ServiceClient.Execute(String soapAction, String message, String[] responseTag, String[] soapNamespaces) in C:\Users\Felipe\Desktop\ACBr.Net.NFSe-master\src\ACBr.Net.NFSe\Providers\NFSeSOAP11ServiceClient.cs:line 104
   at ACBr.Net.NFSe.Providers.CoplanServiceClient.Execute(String action, String message, String[] responseTag) in C:\Users\Felipe\Desktop\ACBr.Net.NFSe-master\src\ACBr.Net.NFSe\Providers\Coplan\CoplanServiceClient.cs:line 220
   at ACBr.Net.NFSe.Providers.CoplanServiceClient.RecepcionarLoteRps(String cabec, String msg) in C:\Users\Felipe\Desktop\ACBr.Net.NFSe-master\src\ACBr.Net.NFSe\Providers\Coplan\CoplanServiceClient.cs:line 79
   at ACBr.Net.NFSe.Providers.ProviderABRASF201.Enviar(Int32 lote, NotaFiscalCollection notas) in C:\Users\Felipe\Desktop\ACBr.Net.NFSe-master\src\ACBr.Net.NFSe\Providers\ProviderABRASF201.cs:line 766

**Comment by rftd** [comment]
Por algum motivo os campos CData estão sendo convertidos para o tipo string na hora de enviar a message, vou estar analisando o motivo.

**Comment by Transis-Felipe** [comment]
Deu certo o envio!

Muito obrigado.

Vou conversar aqui com o financeiro pra tentar contribuir com o padrim.
