### ISSUE TITLE
Dúvida sobre ImprimirPDF

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#75]
Boa tarde,

Como vocês fazem para reimprimir uma nota ?

Atualmente eu só consegui imprimir a nota se passo o parâmetro imprime no momento do envio.

Depois de transmitido como montar o componente de impressão DANFSe para chamar o método ImprimirPDF ?

**Comment by rafd75** [comment]
@transis2 , boa tarde.

O que eu faço é abrir o browser com a URL que aponta para a NFSe... E o usuário imprime por lá.

mas achei interessante essa sua informação sobre passar o parâmetro "imprime" no momento do envio... Como você faz isso?

**Comment by Transis-Felipe** [comment]
oi @rafd75,  é o terceiro parâmetro do enviar.

De onde tu tira a URL ? Que eu saiba apenas algumas prefeituras disponibilizam a url de impressão.

**Comment by rftd** [comment]
Então o componente não tem um componente de impressão ainda, ele tem a classe base mas não tem nada implementado.
Se você tiver implementado ela, basta recarregar o xml da nfse na lista e usar o comando de impressão.

**Comment by rftd** [comment]
Eu adicione um projeto de impressão usando o FastReport, da para usar ele de base se quiser implementar seu próprio componente de impressão. 
Ele não esta completo, mas já da para usar.

**Comment by rafd75** [comment]
@transis2 - bom dia.

Eu vejo a URL consultando uma NFSe já emitida pelo provedor.
E tenho um parâmetro no sistema onde informo essa URL,.

Mas eu não faço a impressão, apenas abro o browser já com a URL da NFSe .... E então o usuário imprime se quiser. Por isso perguntei sobre como você estava fazendo... imprimir na emissão, já vai melhorar bastante aqui. Vou ver esse terceiro parâmetro.
