### ISSUE TITLE
Utilizar CertificadoBytes ao invés do Certificado as String

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#76]
Boa tarde,

Estou tentando fazer o setup do webservice utilizando os bytes de um certificado carregado em memória.

Assim:
oACBrNFSe.Configuracoes.Certificados.CertificadoBytes = BytesCertificado;

Ao invés:
oACBrNFSe.Configuracoes.Certificados.Certificado = "\folderSample\test.pfx";

Mas o ACBr.Net.DFe.Core.Common está dando erro ao chamar o ObterCertificado.

![1](https://user-images.githubusercontent.com/4941173/73768939-a6d6a380-4758-11ea-9a5e-7e21758cb3ae.png)

![2](https://user-images.githubusercontent.com/4941173/73768955-ac33ee00-4758-11ea-80c6-c343c755326d.png)

Vocês sabem se o problema está lá no projeto em delphi do Acbr ou é no nosso componente em C# ?

**Comment by rftd** [comment]
Primeiro este projeto não tem nada haver com o projeto em Pascal do ACBr, são projetos diferentes.
Eu achei um erro na validação aqui, vou estar enviando uma correção.

**Comment by Transis-Felipe** [comment]
Obrigado @rftd 

Este projeto ACBR.Net não consome componentes do projeto em Pascal do ACBr ?

Abraço

**Comment by rftd** [comment]
Não é um projeto todo feito em C#
