### ISSUE TITLE
OptanteSimplesNacional e RegimeEspecialTributacao no mesmo campo

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#77]
Boa tarde,

Acho que temos um problema com relação aos campos do xml virem do mesmo lugar.

Estou tentando montar o XML do RPS com as seguintes informações:

< RegimeEspecialTributacao >*</ RegimeEspecialTributacao >
< OptanteSimplesNacional >1</ OptanteSimplesNacional >

Porém ao enviar nfSe.RegimeEspecialTributacao = RegimeEspecialTributacao.SimplesNacional
o programa está gerando < RegimeEspecialTributacao >9</ RegimeEspecialTributacao>, o que não é aceito pelo provedor Coplan.

O elemento 'http://www.abrasf.org.br/nfse.xsd:RegimeEspecialTributacao' é inválido - O valor '9' é inválido dependendo do tipo de dados 'http://www.abrasf.org.br/nfse.xsd:tsRegimeEspecialTributacao' - Falha na restrição Pattern.

Minha sugestão é separarmos, na classe, os campos OptanteSimplesNacional e RegimeEspecialTributacao

Ou então podemos criar uma derivação, como foi feito para o Ginfes, dentro do Provider

            string regimeEspecialTributacao;
            string optanteSimplesNacional;
            if (nota.RegimeEspecialTributacao == RegimeEspecialTributacao.SimplesNacional)
            {
                regimeEspecialTributacao = "6";
                optanteSimplesNacional = "1";
            }
            else
            {
                regimeEspecialTributacao = ((int)nota.RegimeEspecialTributacao).ToString();
                optanteSimplesNacional = "2";
            }

**Comment by rftd** [comment]
Favor testar a variação do Ginfes, pois eu pretendo mudar muita coisas desta ai de enum, eu planejo remover todos eles igual fiz com o natureza da operação.

**Comment by Transis-Felipe** [comment]
Enviado PR https://github.com/ACBrNet/ACBr.Net.NFSe/pull/79

**Comment by rftd** [comment]
envio uma nova versão favor testar.

**Comment by Transis-Felipe** [comment]
@rftd  Deu certo! Obrigado
