### ISSUE TITLE
Padrim

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#82]
Bom dia @rftd 

Estou tentando me cadastrar no site do Padrim para contribuir mas o link de ativação não funciona.

Já mandei email para o site e não obtive retorno.
Verifiquei outras pessoas reclamando do mesmo problema.

Posso fazer transferência bancária direto pra ti todos os meses para ajudar no projeto ?

Abs

**Comment by rftd** [comment]
Adicionei a opção de usar o Apoia-se

https://apoia.se/acbrnet

**Comment by transis2** [comment]
Feito
