### ISSUE TITLE
Tapurah está aparecendo mais de uma vez

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#83]
Está dando esse erro se rodar o projeto demo e selecionar a cidade de Tapurah

![image](https://user-images.githubusercontent.com/4941173/74378148-2a7d3980-4dc4-11ea-8507-beaffc074048.png)

No combo ela aparece 2x, mas tentei olhar no arquivo de cidades e só aparece uma vez essa cidade lá.

**Comment by rftd** [comment]
a entrada esta duplicada sim, olhe

![image](https://user-images.githubusercontent.com/299476/74387713-aa5cd100-4dcf-11ea-80cd-4f65a2ab6155.png)
