### ISSUE TITLE
Declaração XML inesperada, Provedor Fiorilli

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#86]
Estou com esse erro ao testar o provedor fiorilli com a cidade Estreito/MA

![image](https://user-images.githubusercontent.com/4941173/74443486-0a945700-4e52-11ea-9ded-19eff744f943.png)

Agradeço se puder me ajudar, @rftd

**Comment by rftd** [comment]
tem como postar os arquivos de envio e de retorno do provedor;

**Comment by Transis-Felipe** [comment]
Seguem os arquivos de envio.

[Desktop.zip](https://github.com/ACBrNet/ACBr.Net.NFSe/files/4200214/Desktop.zip)

O arquivo de retorno não chega a ser gerado.

Eu usei o Demo para testar


![image](https://user-images.githubusercontent.com/4941173/74465444-26105980-4e74-11ea-96fb-b092de520586.png)

**Comment by rftd** [comment]
blz vou analisar aqui e já vejo o que pode estar acontecendo

**Comment by rftd** [comment]
Eu mandei um update que talvez resolva seu problema.

**Comment by Transis-Felipe** [comment]
Deu certo, obrigado!
