### ISSUE TITLE
Emissão provedor São Paulo

### ISSUE THREAD

**Issue by sonik-br** [ACBrNet/ACBr.Net.NFSe#91]
Utilizando o aplicativo de testes, configurado para emissão em São Paulo (homologação) e clicando em "Gerar e Enviar Lote RPS" gera o erro:

"Text' é uma expressão XmlNodeType inválida. Linha 1, posição 91."

Erro capturado no arquivo ProviderSaoPaulo.cs, método Enviar(int lote, NotaFiscalCollection notas)

Peço ajuda para solucionar o problema.

**Comment by rftd** [comment]
Correção foi enviada já
