### ISSUE TITLE
Provedor SIGISS

### ISSUE THREAD

**Issue by thiagovalim** [ACBrNet/ACBr.Net.NFSe#95]
Olá, parabéns pelo componente, estou implementando ele junto ao meu projeto. Gostaria de saber se há alguma previsão de implementação do provedor SIGISS ele está disponível no acbr em delphi, gostaria de saber se estará disponível aqui também?

**Comment by rftd** [comment]
Não temos previsão de implementação do mesmo e este projeto não tem relação com o mesmo feito em pascal.

**Comment by angelomachado** [comment]
Olá. Pode ser que eu acabe implementando ele mais pra frente. No momento estou com o ISSNetOnline parcialmente implementado mas está parado pois vou trocar o sistema em um cliente que utiliza e preciso "testar em produção" para concluir, já que homologação é meio reservado. Se quiser meter a mão na massa e implementar fique a vontade que na medida do possível eu te ajudo

**Comment by ievoltecnologia** [comment]
@angelomachado  eu trabalhei para a SigCorp que é a criadora/idealizador do SigISS, possivelmente eu consigo coloca-lo em contato com as pessoas certas para que possamos dar um gás nessa parte. O que acha ?
