### ISSUE TITLE
Contribuir com o projeto 

### ISSUE THREAD

**Issue by feokuma** [ACBrNet/ACBr.Net.NFSe#96]
Notei que não há nenhuma instrução sobre como contribuir com o desenvolvimento do projeto. Gostaria de participar implementando alguns testes automatizados e queria saber se aceitam PR's. Sei que é meio trabalhoso revisar e por isso estou perguntando pra não submeter um PR do nada aí.

Parabéns pelo projeto!

**Comment by rftd** [comment]
Pode submeter em problemas, e quando tiver tempo eu faço as revisões.
