### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by Transis-Felipe** [ACBrNet/ACBr.Net.NFSe#97]
Bom dia @rftd,

Sei que aqui não é o local para isso, mas não encontrei o teu contato em nenhum lugar.

Em qual estado tu mora ? 

Estamos precisando contratar aqui na minha empresa.

**Comment by rftd** [comment]
@transis2 obrigado pela oferta, mas atualmente eu presto serviço a 3 empresas, assim ficando dificil assumir outro compromisso.
