### ISSUE TITLE
Teste do GovDigital que agora e NFe-Cidades

### ISSUE THREAD

**Issue by fabiohcnobre** [ACBrNet/ACBr.Net.NFSe#98]
Gostaria de testar o GovDigital(NFe-Cidades), alguem tem algum de manual como faço isso?

**Comment by rftd** [comment]
basta usar o demo para adicionar a cidade e as url dela e começar a testar

**Comment by fabiohcnobre** [comment]
Rafael fiz isso e estou tendo o seguinte erro:
O elemento 'http://www.abrasf.org.br/nfse.xsd:DataEmissao' é inválido - O valor '2020-05-27T12:34:43' é inválido dependendo do tipo de dados 'http://www.w3.org/2001/XMLSchema:date' - A cadeia de caracteres '2020-05-27T12:34:43' não é um valor Date válido.

**Comment by fabiohcnobre** [comment]
Ele(Schemas) usa um Date e no acbrNFSe está DateTime;
nfSe.IdentificacaoRps.DataEmissao = DateTime.Now;

**Comment by rftd** [comment]
é so mudar a classe base da classe ProviderGovDigital para ProviderABRASF201

**Comment by fabiohcnobre** [comment]
Fiz então dois pull 
 ProviderGovDigital para ProviderABRASF201 (estava ProviderABRASF202)
E alterei a GovDigitalServiceClient para NFSeSOAP11ServiceClient.
Posso lançar um PULL?

**Comment by rftd** [comment]
sim pode

**Comment by fabiohcnobre** [comment]
Pronto fiz dois Pull e estou fechando aqui. 
Obrigado.
